/**
 * SHORTCOIN — the Robinhood Chain universe.
 *
 * GENERATED by scripts/gen-assets.ts. Edit that script, not this file.
 *
 * The universe is coins only: 106 of them, native to Robinhood Chain or
 * launched through Pons. Tokenized equities are not listed — SHORTCOIN does not
 * sell a short on a share.
 *
 * What is real here: the ticker symbols, the names, the sector taxonomy, the launch
 * dates and the contract addresses that were read on-chain.
 *
 * What is invented: every price, every liquidity, holder and volume figure, and every
 * rate. Those exist to populate a simulation.
 */

import type { Asset, AssetClass, MarketPhase, ShortRoute } from './types'
import { between, rng } from './rng'

export const CHAIN = {
  name: 'Robinhood Chain',
  short: 'RHC',
  /** Verified via eth_chainId returning 0x1237. */
  chainId: 4663,
  rpc: 'https://rpc.mainnet.chain.robinhood.com',
  explorer: 'https://robinhoodchain.blockscout.com',
  gasToken: 'ETH',
  /** Global Dollar is the chain's primary quote asset, not USDC. */
  settlement: 'USDG',
  settlementAddress: '0x5fc5360D0400a0Fd4f2af552ADD042D716F1d168',
  blockTimeMs: 100,
  stack: 'Arbitrum Orbit',
} as const

/** Census of the listed universe. The infinite tail is generated on top. */
export const SHORT_CENSUS = {
  total: 106,
  coins: 106,
} as const

interface Seed {
  t: string
  n: string
  s: string
  p: number
  a: string
  real: boolean
  r: ShortRoute
  col: boolean
  whole: boolean
  mult: number
  v: number
  c: AssetClass
  q: string
  age: number
  tier: number
  /** Real market cap in USD for Pons launches; 0 when it should be derived. */
  mc: number
  /** Graduation progress 0..100, or -1 when the concept does not apply. */
  gp: number
  lp: string
}

const SEEDS: Seed[] = [
  {"t":"PONS","n":"Pons","s":"Launchpad","p":0.5978,"a":"0x39dbed3a2bd333467115de45665cc57f813c4571","real":true,"r":"none","col":false,"whole":false,"mult":1,"v":1.45,"c":"coin","q":"USDG","age":1704,"tier":3,"mc":0,"gp":-1,"lp":""},
  {"t":"CASHCAT","n":"Cash Cat","s":"Memecoin","p":0.04128,"a":"0x5c685b84fdf75a8c8cee80e40a7a98a86481b280","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":1.42,"c":"coin","q":"USDG","age":1632,"tier":3,"mc":0,"gp":-1,"lp":""},
  {"t":"WETH","n":"Wrapped Ether","s":"Infrastructure","p":2431.6,"a":"0x2ba03c5dff6ecc144748e516ddeea74c822108cb","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.62,"c":"coin","q":"USDG","age":1704,"tier":3,"mc":0,"gp":-1,"lp":""},
  {"t":"AI","n":"Artificial Inu","s":"Stock-paired meme","p":0.013842,"a":"0xf3848311f9576e22250a83f85a62ad8be7ac3803","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":1.58,"c":"coin","q":"NVDA","age":1392,"tier":2,"mc":0,"gp":-1,"lp":""},
  {"t":"DOGO","n":"Dogo","s":"Memecoin","p":0.009164,"a":"0x8fd069caae093dd74142cb3570015569650db45f","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":1.58,"c":"coin","q":"USDG","age":1488,"tier":2,"mc":0,"gp":-1,"lp":""},
  {"t":"PIPEDOG","n":"Pipedog","s":"Memecoin","p":0.002471,"a":"0x34fb34ce305ccd9eff2075b89ad113c4fcc23c74","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":1.58,"c":"coin","q":"USDG","age":1320,"tier":2,"mc":0,"gp":-1,"lp":""},
  {"t":"MOW","n":"Mow","s":"Memecoin","p":0.00084217,"a":"0x05631fc794bbbf0a674b5458a877da25595cd247","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":1.58,"c":"coin","q":"USDG","age":984,"tier":2,"mc":0,"gp":-1,"lp":""},
  {"t":"TENDIES","n":"Tendies","s":"Memecoin","p":0.00196402,"a":"0xd4bf16288e926936abcfa45313c002ff2c57fa3b","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":1.58,"c":"coin","q":"USDG","age":1176,"tier":2,"mc":0,"gp":-1,"lp":""},
  {"t":"HMM","n":"Hmm","s":"Memecoin","p":0.00031845,"a":"0xd1e9ace48f60a40ce5f0d38f6cdba19cfbde2299","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":1.74,"c":"coin","q":"USDG","age":792,"tier":1,"mc":0,"gp":-1,"lp":""},
  {"t":"STONKBROKER","n":"Stonkbroker","s":"Stock-paired meme","p":0.00006428,"a":"0xb649ef685fc6012c46f0ee71c8e5114e2c330272","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":1.74,"c":"coin","q":"SPY","age":648,"tier":1,"mc":0,"gp":-1,"lp":""},
  {"t":"MEME","n":"Meme","s":"Memecoin","p":0.00412069,"a":"0xd436740618bb933032c4cc561f4973dfd231815c","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":1.74,"c":"coin","q":"USDG","age":576,"tier":1,"mc":0,"gp":-1,"lp":""},
  {"t":"CINEMA","n":"Cinema","s":"Memecoin","p":0.00008912,"a":"0x4646c7c0f557560b934ff289912c14ba38496165","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":1.74,"c":"coin","q":"USDG","age":384,"tier":1,"mc":0,"gp":-1,"lp":""},
  {"t":"SHRUB","n":"Shrub","s":"Memecoin","p":0.00001274,"a":"0xda44e78290f401b9412603904e4b3a96761d42b4","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":1.74,"c":"coin","q":"USDG","age":216,"tier":1,"mc":0,"gp":-1,"lp":""},
  {"t":"ZTHA","n":"Zero To Hero Academy","s":"Launchpad","p":0.0000411403,"a":"0x74107707964A2F5344470Fb3F11c5Db955851654","real":true,"r":"none","col":false,"whole":false,"mult":1,"v":3.79,"c":"coin","q":"ETH","age":22,"tier":0,"mc":41140,"gp":87,"lp":"Pons"},
  {"t":"NEX","n":"Nexsets","s":"Launchpad","p":0.0000234481,"a":"0xB62a51F2572E2Fe6f98a2338c8D33bdaC917D6B3","real":true,"r":"none","col":false,"whole":false,"mult":1,"v":2.894,"c":"coin","q":"ETH","age":22,"tier":0,"mc":23448,"gp":55,"lp":"Pons"},
  {"t":"MATRIX","n":"d-Matrix","s":"Stock-paired meme","p":0.0000189896,"a":"0x097A372e6557c2C69bD09D1aD9d190Cd1a11ee73","real":true,"r":"none","col":false,"whole":false,"mult":1,"v":3.795,"c":"coin","q":"NVDA","age":22,"tier":0,"mc":18990,"gp":51,"lp":"Pons"},
  {"t":"DATACENTER","n":"Datacenter","s":"Stock-paired meme","p":0.0000181452,"a":"0xB31052F36A3cc2a763AeC65d4f2D38b9991b59F6","real":true,"r":"none","col":false,"whole":false,"mult":1,"v":2.867,"c":"coin","q":"MSFT","age":22,"tier":0,"mc":18145,"gp":55,"lp":"Pons"},
  {"t":"ODDSLY","n":"mymind.icu","s":"Launchpad","p":0.0000171142,"a":"0xc21d89D3D56b619bD8E02642C1BC742279f48675","real":true,"r":"none","col":false,"whole":false,"mult":1,"v":3.663,"c":"coin","q":"ETH","age":22,"tier":0,"mc":17114,"gp":41,"lp":"Pons"},
  {"t":"STONKFLY","n":"StonkFlyRH","s":"Stock-paired meme","p":0.0000127047,"a":"0xF12F616a0c02ee0dB385e0077D54cc07583676cB","real":true,"r":"none","col":false,"whole":false,"mult":1,"v":3.009,"c":"coin","q":"GOOGL","age":22,"tier":0,"mc":12705,"gp":40,"lp":"Pons"},
  {"t":"TIMELESS","n":"Book of Maye Musk","s":"Launchpad","p":0.0000116367,"a":"0xe247D668dEB4e07736bb3F655960309Cb7219e9d","real":true,"r":"none","col":false,"whole":false,"mult":1,"v":3.486,"c":"coin","q":"ETH","age":22,"tier":0,"mc":11637,"gp":27,"lp":"Pons"},
  {"t":"STOCK","n":"StockFighters","s":"Launchpad","p":0.0000111701,"a":"0x9d8c66d7a82fE67fC3B1015912986feE757a6c0C","real":true,"r":"none","col":false,"whole":false,"mult":1,"v":3.019,"c":"coin","q":"ETH","age":22,"tier":0,"mc":11170,"gp":26,"lp":"Pons"},
  {"t":"BOB","n":"Microsoft BOB","s":"Stock-paired meme","p":0.0000109412,"a":"0xa76790b297bd717FF1F5414aa6de94D4ce1e910b","real":true,"r":"none","col":false,"whole":false,"mult":1,"v":2.891,"c":"coin","q":"MSFT","age":22,"tier":0,"mc":10941,"gp":34,"lp":"Pons"},
  {"t":"ROAM","n":"ROAM","s":"Launchpad","p":0.00000957084,"a":"0x44cd5866d8Ba814A877B7E50848aFdB786F37fAf","real":true,"r":"none","col":false,"whole":false,"mult":1,"v":3.425,"c":"coin","q":"ETH","age":22,"tier":0,"mc":9571,"gp":20,"lp":"Pons"},
  {"t":"CAPSULE","n":"Capsule","s":"Launchpad","p":0.00000834934,"a":"0x0E37DD66ee57BAAf09C6D4AC35879a90B6B53119","real":true,"r":"none","col":false,"whole":false,"mult":1,"v":2.671,"c":"coin","q":"ETH","age":22,"tier":0,"mc":8349,"gp":16,"lp":"Pons"},
  {"t":"TDS","n":"The Dust Sender","s":"Launchpad","p":0.00000812957,"a":"0xD3F6C6445685A55Be4728924b12FdBA6A4cC1ae2","real":true,"r":"none","col":false,"whole":false,"mult":1,"v":3.821,"c":"coin","q":"USDG","age":22,"tier":0,"mc":8130,"gp":23,"lp":"Pons"},
  {"t":"CHUCK","n":"Chuckboard","s":"Stock-paired meme","p":0.00000806704,"a":"0x720169ba699B5b623979dc6767b4332551BD9139","real":true,"r":"none","col":false,"whole":false,"mult":1,"v":2.892,"c":"coin","q":"SPCX","age":22,"tier":0,"mc":8067,"gp":16,"lp":"Pons"},
  {"t":"PVEL","n":"Pons Velocity","s":"Launchpad","p":0.0000078916,"a":"0xC74b3C874F71AB3036BEBFFb91274f4dfC954c4A","real":true,"r":"none","col":false,"whole":false,"mult":1,"v":2.231,"c":"coin","q":"ETH","age":982,"tier":0,"mc":7892,"gp":17,"lp":"Pons"},
  {"t":"MEOWCRAFT","n":"Meowcraft","s":"Stock-paired meme","p":0.0000076847,"a":"0x6dDb939235A7A7E4C60572ef9D8db31F3dd6a856","real":true,"r":"none","col":false,"whole":false,"mult":1,"v":3.214,"c":"coin","q":"MSFT","age":22,"tier":0,"mc":7685,"gp":22,"lp":"Pons"},
  {"t":"MESS","n":"Mess Crate","s":"Stock-paired meme","p":0.00000742932,"a":"0xAA46fE4aF8e13351600fd96DabB3608eeA670474","real":true,"r":"none","col":false,"whole":false,"mult":1,"v":3.121,"c":"coin","q":"SPCX","age":22,"tier":0,"mc":7429,"gp":13,"lp":"Pons"},
  {"t":"RICHCAT","n":"RichCat","s":"Launchpad","p":0.00000739716,"a":"0x00bAF4d1dd8510E411c27F33A8570f3F826b966E","real":true,"r":"none","col":false,"whole":false,"mult":1,"v":2.493,"c":"coin","q":"ETH","age":982,"tier":0,"mc":7397,"gp":14,"lp":"Pons"},
  {"t":"PORB","n":"Pons Orbit","s":"Launchpad","p":0.00000729321,"a":"0xeBA4dC2ff33FcC9eaA2f8170956C407179F58D55","real":true,"r":"none","col":false,"whole":false,"mult":1,"v":1.969,"c":"coin","q":"ETH","age":982,"tier":0,"mc":7293,"gp":11,"lp":"Pons"},
  {"t":"WENDY","n":"Justice For Wendy","s":"Launchpad","p":0.00000707005,"a":"0x5148513229A1c6EF2cdc0cc2eAdb378b58309b12","real":true,"r":"none","col":false,"whole":false,"mult":1,"v":3.319,"c":"coin","q":"ETH","age":22,"tier":0,"mc":7070,"gp":13,"lp":"Pons"},
  {"t":"CANTLE","n":"Cantle Star","s":"Stock-paired meme","p":0.00000669072,"a":"0x85D63C3F193245fc9ea2b2085b5535BAEcD971D6","real":true,"r":"none","col":false,"whole":false,"mult":1,"v":4.223,"c":"coin","q":"SPCX","age":22,"tier":0,"mc":6691,"gp":1,"lp":"Pons"},
  {"t":"ETHCAT","n":"Ethereum Cat","s":"Launchpad","p":0.00000662037,"a":"0x99b88a9CC59861E2D03F2Ab31850A031F06970dC","real":true,"r":"none","col":false,"whole":false,"mult":1,"v":3.556,"c":"coin","q":"ETH","age":22,"tier":0,"mc":6620,"gp":11,"lp":"Pons"},
  {"t":"PPULSE","n":"Pons Pulse","s":"Launchpad","p":0.0000064953,"a":"0x82C6A15059aBdC959659bFe5CC3ddb34351D59eA","real":true,"r":"none","col":false,"whole":false,"mult":1,"v":1.562,"c":"coin","q":"ETH","age":982,"tier":0,"mc":6495,"gp":13,"lp":"Pons"},
  {"t":"MRM","n":"Mirror Market","s":"Launchpad","p":0.00000640243,"a":"0x2a032fCa5eB97DA933E48fe1AcDb8E261bd788C8","real":true,"r":"none","col":false,"whole":false,"mult":1,"v":4.372,"c":"coin","q":"ETH","age":22,"tier":0,"mc":6402,"gp":0,"lp":"Pons"},
  {"t":"HOLOMUTT","n":"Holomutt","s":"Stock-paired meme","p":0.00000632751,"a":"0xBCB22aCd0cd06ef0F7B785072bAc7b9844132b3D","real":true,"r":"none","col":false,"whole":false,"mult":1,"v":4.124,"c":"coin","q":"SPCX","age":22,"tier":0,"mc":6328,"gp":1,"lp":"Pons"},
  {"t":"ECHOCAT","n":"Sonar Stray","s":"Stock-paired meme","p":0.00000621495,"a":"0x0A463aEb44ab7eA4960eE428723184C9Cb963e71","real":true,"r":"none","col":false,"whole":false,"mult":1,"v":3.881,"c":"coin","q":"SPCX","age":22,"tier":0,"mc":6215,"gp":1,"lp":"Pons"},
  {"t":"FLTRACE","n":"Fault Trace","s":"Stock-paired meme","p":0.00000617415,"a":"0xD925329d0cc799EED6C90FB375AC07cCc2CA3d9C","real":true,"r":"none","col":false,"whole":false,"mult":1,"v":3.697,"c":"coin","q":"SPCX","age":22,"tier":0,"mc":6174,"gp":0,"lp":"Pons"},
  {"t":"LOGICBOT","n":"Logicbot Leaflet","s":"Stock-paired meme","p":0.00000610836,"a":"0x4BB2cb6C22332C686fD255EA559C42264019c912","real":true,"r":"none","col":false,"whole":false,"mult":1,"v":3.047,"c":"coin","q":"SPCX","age":22,"tier":0,"mc":6108,"gp":0,"lp":"Pons"},
  {"t":"ELON","n":"Eloncoin","s":"Stock-paired meme","p":0.00000599831,"a":"0x13947bFca5fbcB37CeCbF90C2744DA33106a563f","real":true,"r":"none","col":false,"whole":false,"mult":1,"v":3.576,"c":"coin","q":"SPCX","age":22,"tier":0,"mc":5998,"gp":8,"lp":"Pons"},
  {"t":"MIDORUCAT","n":"The XBOX Cat","s":"Stock-paired meme","p":0.00000594892,"a":"0xba93fB4FDDDBba523f24cee7502453C3788A73Bd","real":true,"r":"none","col":false,"whole":false,"mult":1,"v":2.623,"c":"coin","q":"MSFT","age":22,"tier":0,"mc":5949,"gp":15,"lp":"Pons"},
  {"t":"PATCH","n":"Stereo Patch","s":"Stock-paired meme","p":0.00000589578,"a":"0xE591cb23fD1F697E52b5a94b4bDa681c3c8613B1","real":true,"r":"none","col":false,"whole":false,"mult":1,"v":3.141,"c":"coin","q":"SPCX","age":22,"tier":0,"mc":5896,"gp":1,"lp":"Pons"},
  {"t":"HEIST","n":"Heist","s":"Launchpad","p":0.00000585661,"a":"0x7e659A8C4B6566f6a189528F8e66e7ec6D39D8c0","real":true,"r":"none","col":false,"whole":false,"mult":1,"v":3.25,"c":"coin","q":"ETH","age":22,"tier":0,"mc":5857,"gp":8,"lp":"Pons"},
  {"t":"DOJIMA","n":"Dojima","s":"Launchpad","p":0.00000584213,"a":"0xC842dE1c4ad99f1B36f405B02a4b97f54bbF2E60","real":true,"r":"none","col":false,"whole":false,"mult":1,"v":3.338,"c":"coin","q":"ETH","age":22,"tier":0,"mc":5842,"gp":7,"lp":"Pons"},
  {"t":"HWYRUN","n":"Guardrail Runner","s":"Stock-paired meme","p":0.00000583559,"a":"0x7e5447560ae74Bb1E3A0091DCd83328411be6d9f","real":true,"r":"none","col":false,"whole":false,"mult":1,"v":4.019,"c":"coin","q":"SPCX","age":22,"tier":0,"mc":5836,"gp":1,"lp":"Pons"},
  {"t":"MERIDIAN","n":"Charred Meridian","s":"Stock-paired meme","p":0.00000580164,"a":"0x135b0389D60a62b4109d3d9EcF1437091e200D90","real":true,"r":"none","col":false,"whole":false,"mult":1,"v":3.383,"c":"coin","q":"SPCX","age":22,"tier":0,"mc":5802,"gp":0,"lp":"Pons"},
  {"t":"XOGE","n":"xoge","s":"Stock-paired meme","p":0.00000579203,"a":"0xeB81E08299472E66347d0dfD4BCD7Fd504b4c7b0","real":true,"r":"none","col":false,"whole":false,"mult":1,"v":2.668,"c":"coin","q":"SPCX","age":22,"tier":0,"mc":5792,"gp":6,"lp":"Pons"},
  {"t":"MIDAS","n":"au2","s":"Launchpad","p":0.00000578758,"a":"0x0585bA06b854a1b42884f48913a2Dfdc0C459b16","real":true,"r":"none","col":false,"whole":false,"mult":1,"v":3.615,"c":"coin","q":"ETH","age":22,"tier":0,"mc":5788,"gp":7,"lp":"Pons"},
  {"t":"XCAT","n":"XCAT","s":"Stock-paired meme","p":0.00000577405,"a":"0x743E660441E8e9823C9151B9bD47b15D23D7d0D6","real":true,"r":"none","col":false,"whole":false,"mult":1,"v":3.424,"c":"coin","q":"SPCX","age":22,"tier":0,"mc":5774,"gp":7,"lp":"Pons"},
  {"t":"ESTER","n":"Ester Assay","s":"Stock-paired meme","p":0.00000575372,"a":"0xDf3b238C86eB446d262E91dCf664Dc865b9A6811","real":true,"r":"none","col":false,"whole":false,"mult":1,"v":3.553,"c":"coin","q":"SPCX","age":22,"tier":0,"mc":5754,"gp":0,"lp":"Pons"},
  {"t":"PURRCTL","n":"Purrctl","s":"Stock-paired meme","p":0.00000574476,"a":"0x7D03e48cB4277d5d9e859c881527e885FFeD1F48","real":true,"r":"none","col":false,"whole":false,"mult":1,"v":4.11,"c":"coin","q":"SPCX","age":22,"tier":0,"mc":5745,"gp":1,"lp":"Pons"},
  {"t":"VIRID","n":"Viridian Plinth","s":"Stock-paired meme","p":0.00000573501,"a":"0x7e99295E3E8a69Ea23Af368FA34Ea2250AB337f1","real":true,"r":"none","col":false,"whole":false,"mult":1,"v":2.807,"c":"coin","q":"SPCX","age":22,"tier":0,"mc":5735,"gp":0,"lp":"Pons"},
  {"t":"FAIL","n":"Failed","s":"Launchpad","p":0.00000571677,"a":"0x7300c5724628647ef387732c44e9eE90817f734b","real":true,"r":"none","col":false,"whole":false,"mult":1,"v":3.078,"c":"coin","q":"ETH","age":22,"tier":0,"mc":5717,"gp":7,"lp":"Pons"},
  {"t":"CALIBRE","n":"Meridian Calibre","s":"Stock-paired meme","p":0.00000571229,"a":"0x823d9Fa835e78992F2768065e8613A17F67cec7A","real":true,"r":"none","col":false,"whole":false,"mult":1,"v":3.752,"c":"coin","q":"SPCX","age":22,"tier":0,"mc":5712,"gp":1,"lp":"Pons"},
  {"t":"DEMITASSE","n":"Demitasse Noir","s":"Stock-paired meme","p":0.00000567415,"a":"0xdEE11354C843b039E153eBA3Db58DBBCa2170Cf4","real":true,"r":"none","col":false,"whole":false,"mult":1,"v":3.135,"c":"coin","q":"SPCX","age":22,"tier":0,"mc":5674,"gp":1,"lp":"Pons"},
  {"t":"CHASSIS","n":"Chassis Rose","s":"Stock-paired meme","p":0.00000561385,"a":"0xbB747e0fe738B459C9658dB9B76914162aBAcfDD","real":true,"r":"none","col":false,"whole":false,"mult":1,"v":2.918,"c":"coin","q":"SPCX","age":22,"tier":0,"mc":5614,"gp":1,"lp":"Pons"},
  {"t":"SIRIUS","n":"The Doge Star","s":"Stock-paired meme","p":0.00000558133,"a":"0x47796e2f903cEF8e5bc2F32Ce31578bCf5A03C0C","real":true,"r":"none","col":false,"whole":false,"mult":1,"v":2.876,"c":"coin","q":"SPCX","age":22,"tier":0,"mc":5581,"gp":6,"lp":"Pons"},
  {"t":"GERI","n":"Geri the CFO","s":"Launchpad","p":0.00000557358,"a":"0x36ede7ce24F907bBA045c6F9d51628FE9F627815","real":true,"r":"none","col":false,"whole":false,"mult":1,"v":2.687,"c":"coin","q":"ETH","age":22,"tier":0,"mc":5574,"gp":6,"lp":"Pons"},
  {"t":"XDOGE","n":"X Dodge","s":"Stock-paired meme","p":0.00000550829,"a":"0x098341e75b352DC0AAf978a8EB6A18cC05e1159B","real":true,"r":"none","col":false,"whole":false,"mult":1,"v":3.529,"c":"coin","q":"SPCX","age":22,"tier":0,"mc":5508,"gp":6,"lp":"Pons"},
  {"t":"XCOIN","n":"XCOIN","s":"Stock-paired meme","p":0.00000549234,"a":"0x0dB62bB8EC401054F85502451A32b6bfd76160dc","real":true,"r":"none","col":false,"whole":false,"mult":1,"v":3.267,"c":"coin","q":"SPCX","age":22,"tier":0,"mc":5492,"gp":0,"lp":"Pons"},
  {"t":"VANITAS","n":"Gilt Vanity","s":"Stock-paired meme","p":0.0000054789,"a":"0x66E7DA217447b764DCD1949CD9f8333560E847a2","real":true,"r":"none","col":false,"whole":false,"mult":1,"v":3.233,"c":"coin","q":"SPCX","age":22,"tier":0,"mc":5479,"gp":1,"lp":"Pons"},
  {"t":"WUF","n":"wuf","s":"Stock-paired meme","p":0.00000540284,"a":"0xFfA4A6C67584FB4940e8749b9c88006a612f971A","real":true,"r":"none","col":false,"whole":false,"mult":1,"v":2.617,"c":"coin","q":"SPY","age":22,"tier":0,"mc":5403,"gp":12,"lp":"Pons"},
  {"t":"CLACK","n":"Lucky Clack","s":"Stock-paired meme","p":0.00000538316,"a":"0xe0F493872b82cD0c5347fE77823574FeC46e0109","real":true,"r":"none","col":false,"whole":false,"mult":1,"v":2.869,"c":"coin","q":"SPCX","age":22,"tier":0,"mc":5383,"gp":1,"lp":"Pons"},
  {"t":"CHADPOLE","n":"Chadpole","s":"Launchpad","p":0.00000534827,"a":"0x84aE08BfCa6DF70438a7b043b5E3A1C38A4Ece1d","real":true,"r":"none","col":false,"whole":false,"mult":1,"v":3.4,"c":"coin","q":"ETH","age":22,"tier":0,"mc":5348,"gp":6,"lp":"Pons"},
  {"t":"OPTIMUS","n":"OPTIMUS","s":"Stock-paired meme","p":0.00000534588,"a":"0x7BdF3774323F2B8A48179Ab69A9DFD867b17acf6","real":true,"r":"none","col":false,"whole":false,"mult":1,"v":1.543,"c":"coin","q":"TSLA","age":982,"tier":0,"mc":5346,"gp":8,"lp":"Pons"},
  {"t":"STRANGE","n":"Strange Cat","s":"Launchpad","p":0.00000534356,"a":"0xe191f2509c1389748df0F36311341685A14ee4e9","real":true,"r":"none","col":false,"whole":false,"mult":1,"v":3.381,"c":"coin","q":"ETH","age":22,"tier":0,"mc":5344,"gp":6,"lp":"Pons"},
  {"t":"OZZY","n":"Ozzy","s":"Launchpad","p":0.00000527799,"a":"0xdCceF866192088E383351CC1aa9D87344A247477","real":true,"r":"none","col":false,"whole":false,"mult":1,"v":2.828,"c":"coin","q":"ETH","age":22,"tier":0,"mc":5278,"gp":5,"lp":"Pons"},
  {"t":"MC","n":"Meridian Capital","s":"Launchpad","p":0.00000526094,"a":"0x51bfd247332e78B06b00f3110C8D5000ee8f1321","real":true,"r":"none","col":false,"whole":false,"mult":1,"v":4.369,"c":"coin","q":"ETH","age":22,"tier":0,"mc":5261,"gp":5,"lp":"Pons"},
  {"t":"SACK","n":"Sack Combo","s":"Stock-paired meme","p":0.00000525939,"a":"0x27B9f22375Ad6185eaaFce60B54E86f3489Ee63D","real":true,"r":"none","col":false,"whole":false,"mult":1,"v":3.234,"c":"coin","q":"SPCX","age":22,"tier":0,"mc":5259,"gp":0,"lp":"Pons"},
  {"t":"APSIS","n":"Periapsis","s":"Stock-paired meme","p":0.00000524893,"a":"0x55a816A687770Fd5c9772C0EFD8D78f758a6d90D","real":true,"r":"none","col":false,"whole":false,"mult":1,"v":2.97,"c":"coin","q":"SPCX","age":22,"tier":0,"mc":5249,"gp":0,"lp":"Pons"},
  {"t":"HERDTAG","n":"Herd Tag","s":"Stock-paired meme","p":0.00000523696,"a":"0xD40047187eCC0F421A85515d6802E24ceFaF0340","real":true,"r":"none","col":false,"whole":false,"mult":1,"v":3.376,"c":"coin","q":"SPCX","age":22,"tier":0,"mc":5237,"gp":1,"lp":"Pons"},
  {"t":"AILUR","n":"Ailur Standard","s":"Stock-paired meme","p":0.00000522581,"a":"0xEB2C5aD644B2845a565aaA2a8111f3e10b2dadAE","real":true,"r":"none","col":false,"whole":false,"mult":1,"v":2.782,"c":"coin","q":"SPCX","age":22,"tier":0,"mc":5226,"gp":0,"lp":"Pons"},
  {"t":"TRIAL","n":"Lead Trial","s":"Stock-paired meme","p":0.00000520912,"a":"0xE5c452B132c8237E3034F4d2894496f75a9d8cbE","real":true,"r":"none","col":false,"whole":false,"mult":1,"v":2.999,"c":"coin","q":"SPCX","age":22,"tier":0,"mc":5209,"gp":1,"lp":"Pons"},
  {"t":"RODEO","n":"All-Around Broker","s":"Stock-paired meme","p":0.00000519316,"a":"0x616388E2fcB1Cb843CDb0e2EeffBceC239111FC9","real":true,"r":"none","col":false,"whole":false,"mult":1,"v":3.608,"c":"coin","q":"SPCX","age":22,"tier":0,"mc":5193,"gp":0,"lp":"Pons"},
  {"t":"ANAMORPH","n":"Anamorph","s":"Stock-paired meme","p":0.00000518837,"a":"0x521Fa36225E270c7C24c4f791E89E3e3E57a05B0","real":true,"r":"none","col":false,"whole":false,"mult":1,"v":3.499,"c":"coin","q":"SPCX","age":22,"tier":0,"mc":5188,"gp":0,"lp":"Pons"},
  {"t":"SLIPCAST","n":"Slipcast","s":"Stock-paired meme","p":0.00000518141,"a":"0x1157E3bDDAA606d309C362DB9654722861aA093B","real":true,"r":"none","col":false,"whole":false,"mult":1,"v":3.347,"c":"coin","q":"SPCX","age":22,"tier":0,"mc":5181,"gp":1,"lp":"Pons"},
  {"t":"VESTA","n":"Blowfly Vesta","s":"Stock-paired meme","p":0.00000517484,"a":"0x47308491A5Df3D3ee0cF1E4465DFcFb025491cc2","real":true,"r":"none","col":false,"whole":false,"mult":1,"v":3.288,"c":"coin","q":"SPCX","age":22,"tier":0,"mc":5175,"gp":0,"lp":"Pons"},
  {"t":"BRAND","n":"Stockyard Brand","s":"Stock-paired meme","p":0.00000515852,"a":"0xdc576b7155450528940EE786F1aAcdD8f68e754A","real":true,"r":"none","col":false,"whole":false,"mult":1,"v":4.197,"c":"coin","q":"SPCX","age":22,"tier":0,"mc":5159,"gp":1,"lp":"Pons"},
  {"t":"VIVARIUM","n":"Pocket Vivarium","s":"Stock-paired meme","p":0.00000514539,"a":"0xC54048b32E0caF1062dFa53911e347D3e23fCda2","real":true,"r":"none","col":false,"whole":false,"mult":1,"v":3.968,"c":"coin","q":"SPCX","age":22,"tier":0,"mc":5145,"gp":1,"lp":"Pons"},
  {"t":"MOUSER","n":"Pantry Mouser","s":"Stock-paired meme","p":0.0000051429,"a":"0xe6e6b44224731DBe6093Af4B05E6255e83e28aba","real":true,"r":"none","col":false,"whole":false,"mult":1,"v":3.625,"c":"coin","q":"SPCX","age":22,"tier":0,"mc":5143,"gp":1,"lp":"Pons"},
  {"t":"VLAD","n":"Vlad: The Documentary","s":"Launchpad","p":0.00000511848,"a":"0x804B6966B8a762840dE510c863A33898688552A4","real":true,"r":"none","col":false,"whole":false,"mult":1,"v":2.618,"c":"coin","q":"ETH","age":22,"tier":0,"mc":5118,"gp":0,"lp":"Pons"},
  {"t":"CYBERCAB","n":"Cybercab","s":"Stock-paired meme","p":0.00000508634,"a":"0x930e0eAACd2F092211E4431a88025e6112B39f35","real":true,"r":"none","col":false,"whole":false,"mult":1,"v":3.205,"c":"coin","q":"SPCX","age":22,"tier":0,"mc":5086,"gp":4,"lp":"Pons"},
  {"t":"STRMN","n":"Starman","s":"Stock-paired meme","p":0.00000507765,"a":"0xC8bCeA856Db9A87Cb52518a236E5C2d61798E20f","real":true,"r":"none","col":false,"whole":false,"mult":1,"v":1.702,"c":"coin","q":"SPCX","age":982,"tier":0,"mc":5078,"gp":4,"lp":"Pons"},
  {"t":"GRAV","n":"PONSBALL","s":"Launchpad","p":0.00000506546,"a":"0x6045FFE55C1668568e502337B8Cc58EDAC32122A","real":true,"r":"none","col":false,"whole":false,"mult":1,"v":2.824,"c":"coin","q":"ETH","age":22,"tier":0,"mc":5065,"gp":2,"lp":"Pons"},
  {"t":"RHC","n":"Robinhood Coin","s":"Stock-paired meme","p":0.00000505101,"a":"0x718a8587f3d642c462E1DDcB73ffE82e9c5748D0","real":true,"r":"none","col":false,"whole":false,"mult":1,"v":3.739,"c":"coin","q":"COIN","age":22,"tier":0,"mc":5051,"gp":8,"lp":"Pons"},
  {"t":"DAY","n":"day","s":"Stock-paired meme","p":0.00000502635,"a":"0xF4e52F0BeDa574cEbC8e71CFf0fD9f66a19280f6","real":true,"r":"none","col":false,"whole":false,"mult":1,"v":3.527,"c":"coin","q":"SPCX","age":22,"tier":0,"mc":5026,"gp":4,"lp":"Pons"},
  {"t":"ROGE","n":"Robinhood Doge","s":"Stock-paired meme","p":0.00000497333,"a":"0x33aF8944728935F522774FcC7276d7B20BB7A23c","real":true,"r":"none","col":false,"whole":false,"mult":1,"v":2.635,"c":"coin","q":"SPCX","age":22,"tier":0,"mc":4973,"gp":3,"lp":"Pons"},
  {"t":"LGBT","n":"LGBT+","s":"Stock-paired meme","p":0.0000049387,"a":"0x18421997538e6f18fF3f3F69a5082D1dc166F7cf","real":true,"r":"none","col":false,"whole":false,"mult":1,"v":2.866,"c":"coin","q":"NFLX","age":22,"tier":0,"mc":4939,"gp":5,"lp":"Pons"},
  {"t":"FROG","n":"Spacex Frog","s":"Stock-paired meme","p":0.00000493691,"a":"0x9fDf78cF1ad0deb7115AC8B9e097a3e45F460F60","real":true,"r":"none","col":false,"whole":false,"mult":1,"v":2.711,"c":"coin","q":"SPCX","age":22,"tier":0,"mc":4937,"gp":3,"lp":"Pons"},
  {"t":"FLOKI","n":"Flokicoin","s":"Stock-paired meme","p":0.00000493425,"a":"0x631C242308bFB09723B7C22d5328ea6A9E8a39d5","real":true,"r":"none","col":false,"whole":false,"mult":1,"v":3.146,"c":"coin","q":"SPCX","age":22,"tier":0,"mc":4934,"gp":3,"lp":"Pons"},
  {"t":"ENERGYCOIN","n":"Energycoin","s":"Stock-paired meme","p":0.00000493394,"a":"0x383C3ABB555B2fa0F7eaEE41de15310b6E26b3cC","real":true,"r":"none","col":false,"whole":false,"mult":1,"v":4.048,"c":"coin","q":"SPCX","age":22,"tier":0,"mc":4934,"gp":3,"lp":"Pons"},
  {"t":"ROBINHOOD","n":"ROBINHOOD","s":"Stock-paired meme","p":0.00000492936,"a":"0x210818dE4792FF2acCb4910D96a59dC3781c751b","real":true,"r":"none","col":false,"whole":false,"mult":1,"v":3.643,"c":"coin","q":"SPCX","age":22,"tier":0,"mc":4929,"gp":3,"lp":"Pons"},
  {"t":"401K","n":"Retirement plan","s":"Stock-paired meme","p":0.0000048166,"a":"0xf4A70B06a150c8e1be0F2cd500d12eEAdAE08eab","real":true,"r":"none","col":false,"whole":false,"mult":1,"v":2.55,"c":"coin","q":"SPY","age":982,"tier":0,"mc":4817,"gp":8,"lp":"Pons"},
  {"t":"TSLAMEME","n":"Tesla Memecoin","s":"Stock-paired meme","p":0.00000465287,"a":"0xc825e0AAC20122aa5af5EB69D39f6248460B8e29","real":true,"r":"none","col":false,"whole":false,"mult":1,"v":2.167,"c":"coin","q":"TSLA","age":982,"tier":0,"mc":4653,"gp":4,"lp":"Pons"},
  {"t":"GPONS","n":"gPons","s":"Launchpad","p":0.00000464222,"a":"0x42665abeeb245Ce662dA576cfD7b10F804A259e9","real":true,"r":"none","col":false,"whole":false,"mult":1,"v":3.268,"c":"coin","q":"ETH","age":22,"tier":0,"mc":4642,"gp":3,"lp":"Pons"},
  {"t":"NOKIA","n":"Nokia Starship","s":"Launchpad","p":0.0000044917,"a":"0xf896b3D22979f4B2FbCC3ce112739Ca7f7162146","real":true,"r":"none","col":false,"whole":false,"mult":1,"v":3.026,"c":"coin","q":"ETH","age":22,"tier":0,"mc":4492,"gp":1,"lp":"Pons"},
  {"t":"MARS","n":"Marscoin","s":"Stock-paired meme","p":0.00000447786,"a":"0x2420e6E8b9AbE73088d04F1375debADb359c0F9F","real":true,"r":"none","col":false,"whole":false,"mult":1,"v":1.878,"c":"coin","q":"SPCX","age":982,"tier":0,"mc":4478,"gp":1,"lp":"Pons"},
  {"t":"PIECOIN","n":"Piecoin","s":"Launchpad","p":0.00000445535,"a":"0x6520DeEF0E0A511937bc5acE54eEe6096567E7fA","real":true,"r":"none","col":false,"whole":false,"mult":1,"v":2.815,"c":"coin","q":"USDG","age":22,"tier":0,"mc":4455,"gp":6,"lp":"Pons"},
  {"t":"LOX","n":"loxley.partners","s":"Launchpad","p":0.00000441595,"a":"0x9D777409C8270F37c47A8EE7D5c568b34cffb943","real":true,"r":"none","col":false,"whole":false,"mult":1,"v":3.593,"c":"coin","q":"ETH","age":22,"tier":0,"mc":4416,"gp":1,"lp":"Pons"},
  {"t":"RETRO","n":"Retro Media","s":"Launchpad","p":0.0000044018,"a":"0xcF7022E990F743a948c343f810D93055e2312cF6","real":true,"r":"none","col":false,"whole":false,"mult":1,"v":3.084,"c":"coin","q":"ETH","age":22,"tier":0,"mc":4402,"gp":1,"lp":"Pons"},
  {"t":"BASTEROID","n":"Baby Asteroid","s":"Stock-paired meme","p":0.00000433156,"a":"0xe0Ea205Cf134945Fa706eB7A9eDC4fAd5F60a021","real":true,"r":"none","col":false,"whole":false,"mult":1,"v":2.414,"c":"coin","q":"SPCX","age":982,"tier":0,"mc":4332,"gp":0,"lp":"Pons"},
  {"t":"APPLS","n":"Apple Stock","s":"Launchpad","p":0.00000431003,"a":"0x1D012d707825db4563Ac5ED92B560421c6bC0Efe","real":true,"r":"none","col":false,"whole":false,"mult":1,"v":4.375,"c":"coin","q":"ETH","age":22,"tier":0,"mc":4310,"gp":0,"lp":"Pons"},
  {"t":"ELONCOIN","n":"Eloncoin","s":"Stock-paired meme","p":0.00000507938,"a":"0x84b527A4753014b46Ab9035A052f16006a8B20B0","real":true,"r":"none","col":false,"whole":false,"mult":1,"v":3.311,"c":"coin","q":"SPCX","age":22,"tier":0,"mc":5079,"gp":4,"lp":"Pons"},
  {"t":"ElonCoin","n":"Eloncoin","s":"Stock-paired meme","p":0.00000530542,"a":"0x870E2eb30A037889Be4018eA9Ab3D402Bf5bc2Cc","real":true,"r":"none","col":false,"whole":false,"mult":1,"v":4.097,"c":"coin","q":"SPCX","age":22,"tier":0,"mc":5305,"gp":4,"lp":"Pons"},
  {"t":"eloncoin","n":"ELONCOIN","s":"Stock-paired meme","p":0.00000539855,"a":"0xD9f4A8Af6622039B1BCb643Eb6D034FAcf8ACF91","real":true,"r":"none","col":false,"whole":false,"mult":1,"v":2.915,"c":"coin","q":"SPCX","age":22,"tier":0,"mc":5399,"gp":0,"lp":"Pons"},
]

function build(seed: Seed): Asset {
  const next = rng(`rhc:${seed.t}:mkt`)
  const isCoin = seed.c === 'coin'

  const vol = seed.v * between(next, 0.85, 1.25)
  const drift = between(next, -0.24, 0.34)
  const isEtf = seed.s.startsWith('ETF')

  // A memecoin does not move like a share. Nothing arbitrages it back to a
  // fair value, so the daily range is measured in tens of percent and the
  // youngest names are the wildest.
  const swing = isCoin ? (seed.tier >= 2 ? 26 : 55) : isEtf ? 2.7 : 9
  const change24h = between(next, -swing, swing)
  const change1h = change24h * between(next, 0.05, 0.5) + between(next, -1.4, 1.4) * (isCoin ? 6 : 1)
  const change7d = change24h * between(next, 0.6, 2.4)

  // Depth. A Pons launch reports its real market cap, and everything about a
  // token that size follows from it: a $5K token has a few thousand dollars of
  // pool behind it, not a derived multiple.
  const isPons = seed.mc > 0
  const tier = isCoin
    ? ([0.02, 0.12, 0.8, 4] as const)[seed.tier] ?? 0.05
    : seed.r === 'borrow'
      ? 6
      : seed.r === 'perp'
        ? 2.4
        : 0.7

  const marketCap = isPons ? seed.mc : 0
  const liquidity = isPons
    ? marketCap * between(next, 0.06, 0.3)
    : between(next, 0.4e6, 18e6) * tier
  // Coins turn over their own float many times a day. Equities do not.
  const volume24h = liquidity * (isCoin ? between(next, 1.2, 14) : between(next, 0.4, 5.6))

  // Borrow is the price of a short, so it is expensive exactly where shorting is
  // hard — which on this chain is almost everywhere, and worst of all on coins
  // that no lender will touch.
  const borrowFee = isCoin
    ? between(next, 0.6, 3.2) - seed.tier * 0.12
    : seed.r === 'none'
      ? between(next, 0.22, 0.95)
      : seed.r === 'perp'
        ? between(next, 0.03, 0.28)
        : between(next, 0.005, 0.06)

  const shortInterest = isCoin
    ? between(next, 0.0, 0.08)
    : seed.r === 'none'
      ? between(next, 0.02, 0.18)
      : between(next, 0.12, 0.66)
  const fundingRate = (shortInterest - 0.5) * -between(next, 0.0004, 0.0055)

  return {
    symbol: seed.t,
    underlying: isCoin ? undefined : seed.t,
    name: seed.n,
    /** The on-chain ERC-20 name. Stock tokens carry the issuer suffix; coins do not. */
    tokenName: isCoin ? seed.n : `${seed.n} • Robinhood Token`,
    sector: seed.s,
    assetClass: seed.c,
    quote: seed.q,
    ageHours: isCoin ? seed.age : undefined,
    graduationPct: seed.gp >= 0 ? seed.gp : undefined,
    launchpad: seed.lp || undefined,
    private: seed.t === 'SPCX',
    address: seed.a,
    verifiedAddress: seed.real,
    logoHue: Math.floor(next() * 360),
    price: seed.p,
    anchor: seed.p,
    change1h,
    change24h,
    change7d,
    volume24h,
    liquidity,
    marketCap: isPons ? marketCap : liquidity * (isCoin ? between(next, 8, 60) : between(next, 40, 900)),
    holders: isPons
      ? Math.floor(between(next, 8, 240))
      : Math.floor(
          between(next, 240, 96_000) *
            (isCoin ? 0.05 + seed.tier * 0.4 : seed.r === 'none' ? 0.4 : 1),
        ),
    borrowFee,
    fundingRate,
    shortInterest,
    openInterest: liquidity * between(next, 0.2, 1.8),
    phase: 'open' as MarketPhase,
    vol,
    drift,
    shortRoute: seed.r,
    collateralOnly: seed.col,
    wholeSharesOnly: seed.whole,
    uiMultiplier: seed.mult,
  }
}

export const ASSETS: Asset[] = SEEDS.map(build)

export const ASSET_BY_SYMBOL: Record<string, Asset> = Object.fromEntries(
  ASSETS.map((a) => [a.symbol, a]),
)

export function getAsset(symbol: string): Asset | undefined {
  return ASSET_BY_SYMBOL[symbol]
}

export const SECTORS: string[] = ["Infrastructure", "Launchpad", "Memecoin", "Stock-paired meme"]

/** Sectors carried by the chain's own coins, Pons launches excluded. */
export const COIN_SECTORS: string[] = ["Infrastructure", "Launchpad", "Memecoin", "Stock-paired meme"]

export const COINS: Asset[] = ASSETS

/** Quote assets that are money rather than a company. */
export const CASH_QUOTES = ['USDG', 'ETH', 'cbBTC', 'WETH'] as const

/**
 * True when a token's pool is quoted against a tokenized equity rather than
 * money — the pairing Robinhood Chain invented. Shorting one of these is a bet
 * on the coin RELATIVE to the share it is paired with, not against the dollar.
 */
export function isStockPaired(a: Asset): boolean {
  return a.assetClass === 'coin' && !CASH_QUOTES.includes(a.quote as (typeof CASH_QUOTES)[number])
}

export const SHORT_ROUTE_LABEL: Record<ShortRoute, string> = {
  borrow: 'Spot borrow',
  perp: 'Perp only',
  none: 'No short route',
}

/**
 * Equity market phase for a given moment, US Eastern.
 *
 * Coins trade on-chain 24/7, but a stock-paired pool's reference venue does not — and the
 * mint/burn window that lets authorised participants arbitrage the peg is only open
 * Monday 02:00 CET through Saturday 02:00 CET. Outside it, nothing keeps the token
 * tied to the share, and spreads widen. That is a real property of this asset class
 * and the interface has to say so.
 */
export function marketPhase(now = new Date()): MarketPhase {
  const et = new Date(now.toLocaleString('en-US', { timeZone: 'America/New_York' }))
  const day = et.getDay()
  const minutes = et.getHours() * 60 + et.getMinutes()
  if (day === 0 || day === 6) return 'closed'
  if (minutes >= 570 && minutes < 960) return 'open'
  if (minutes >= 240 && minutes < 570) return 'pre'
  if (minutes >= 960 && minutes < 1200) return 'after'
  return 'closed'
}

export const PHASE_LABEL: Record<MarketPhase, string> = {
  open: 'Market open',
  pre: 'Pre-market',
  after: 'After hours',
  closed: 'Market closed',
}

/**
 * Whether the mint/burn window is open. When it is shut there is no authorised
 * participant arbitrage, so the token can drift from the share it tracks.
 */
export function tokenizationWindowOpen(now = new Date()): boolean {
  const cet = new Date(now.toLocaleString('en-US', { timeZone: 'Europe/Paris' }))
  const day = cet.getDay()
  const hour = cet.getHours()
  if (day === 6) return hour < 2
  if (day === 0) return false
  if (day === 1) return hour >= 2
  return true
}
