/**
 * SHORTCOIN — the Robinhood Chain universe.
 *
 * GENERATED by scripts/gen-assets.ts. Edit that script, not this file.
 *
 * What is real here: the 213 ticker symbols, the company names, the sector
 * taxonomy, the contract addresses that were read on-chain, the ERC-8056 uiMultiplier
 * values, and — most importantly — which tokens actually have a way to be shorted today.
 *
 * What is invented: every price, every liquidity, holder and volume figure, every borrow
 * and funding rate. Those exist to populate a simulation.
 *
 * The short-route census is the whole reason this product exists:
 *   5 tokens have a spot borrow market (all of them sitting at zero supplied)
 *   39 tokens have a perp somewhere
 *   169 tokens — 79% of the chain — have no way to go short at all
 */

import type { Asset, AssetClass, MarketPhase, ShortRoute } from './types'
import { between, rng } from './rng'

export const CHAIN = {
  name: 'Robinhood Chain',
  short: 'RHC',
  /** Verified via eth_chainId returning 0x1237. */
  chainId: 4663,
  rpc: 'https://rpc.mainnet.chain.robinhood.com',
  explorer: 'https://robinhoodchain.blockscout.com',
  gasToken: 'ETH',
  /** Global Dollar is the chain's primary quote asset, not USDC. */
  settlement: 'USDG',
  settlementAddress: '0x5fc5360D0400a0Fd4f2af552ADD042D716F1d168',
  blockTimeMs: 100,
  stack: 'Arbitrum Orbit',
} as const

/** Census of how shortable this chain actually is. Drives the product's pitch. */
export const SHORT_CENSUS = {
  total: 213,
  equities: 195,
  coins: 18,
  borrow: 5,
  perp: 39,
  none: 169,
} as const

interface Seed {
  t: string
  n: string
  s: string
  p: number
  a: string
  real: boolean
  r: ShortRoute
  col: boolean
  whole: boolean
  mult: number
  v: number
  c: AssetClass
  q: string
  age: number
  tier: number
}

const SEEDS: Seed[] = [
  {"t":"AAPL","n":"Apple","s":"Technology","p":268.42,"a":"0xaF3D76f1834A1d425780943C99Ea8A608f8a93f9","real":true,"r":"borrow","col":false,"whole":false,"mult":1.000566,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"TSLA","n":"Tesla","s":"Automotive","p":412.9,"a":"0x322F0929c4625eD5bAd873c95208D54E1c003b2d","real":true,"r":"borrow","col":false,"whole":false,"mult":1,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"NVDA","n":"NVIDIA","s":"Semiconductors","p":214.86,"a":"0xd0601CE157Db5bdC3162BbaC2a2C8aF5320D9EEC","real":true,"r":"borrow","col":false,"whole":false,"mult":1.000775,"v":0.46,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"MSFT","n":"Microsoft","s":"Technology","p":512.63,"a":"0xe93237C50D904957Cf27E7B1133b510C669c2e74","real":true,"r":"perp","col":false,"whole":false,"mult":1,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"AMZN","n":"Amazon","s":"Consumer Discretionary","p":246.71,"a":"0x12f190a9F9d7D37a250758b26824B97CE941bF54","real":true,"r":"perp","col":false,"whole":false,"mult":1,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"GOOGL","n":"Alphabet Inc. Class A","s":"Technology","p":289.54,"a":"0x2e0847E8910a9732eB3fb1bb4b70a580ADAD4FE3","real":true,"r":"borrow","col":false,"whole":false,"mult":1,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"META","n":"Meta Platforms","s":"Technology","p":724.31,"a":"0xc0D6457C16Cc70d6790Dd43521C899C87ce02f35","real":true,"r":"perp","col":false,"whole":false,"mult":1,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"SPCX","n":"Space Exploration Technologies (SpaceX)","s":"Space & Satellite","p":226.4,"a":"0x4a0E65A3EcceC6dBe60AE065F2e7bb85Fae35eEa","real":true,"r":"perp","col":false,"whole":false,"mult":1,"v":0.72,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"SPY","n":"SPDR S&P 500 ETF Trust","s":"ETF - US Equity","p":712.4,"a":"0x117cc2133c37B721F49dE2A7a74833232B3B4C0C","real":true,"r":"borrow","col":false,"whole":false,"mult":1,"v":0.19,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"QQQ","n":"Invesco QQQ","s":"ETF - US Equity","p":618.9,"a":"0xD5f3879160bc7c32ebb4dC785F8a4F505888de68","real":true,"r":"perp","col":false,"whole":false,"mult":1,"v":0.19,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"COIN","n":"Coinbase","s":"Crypto Financials","p":342.6,"a":"0x6330D8C3178a418788dF01a47479c0ce7CCF450b","real":true,"r":"perp","col":false,"whole":false,"mult":1,"v":0.74,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"MSTR","n":"Strategy Inc. (MicroStrategy)","s":"Crypto Treasury","p":268.42,"a":"0xec262a75e413fAfD0dF80480274532C79D42da09","real":true,"r":"perp","col":false,"whole":false,"mult":1,"v":0.88,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"QCOM","n":"Qualcomm","s":"Semiconductors","p":186.2,"a":"0x0f17206447090e464C277571124dD2688E48AEA9","real":true,"r":"perp","col":false,"whole":false,"mult":1,"v":0.46,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"CRM","n":"Salesforce","s":"Software","p":248.12,"a":"0xd95B44124e475743a7589e68F3D74008A5536D44","real":true,"r":"none","col":true,"whole":false,"mult":1,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"P","n":"Everpure Inc.","s":"Industrials","p":208.86,"a":"0x1Cdad396DB64BDa184d5182A97Dd9B3C62100b7D","real":true,"r":"none","col":false,"whole":false,"mult":1,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"AAOI","n":"Applied Optoelectronics","s":"Semiconductors","p":344.68,"a":"0x23b152ee7e97de6deaeadf43a2bfe225eedcb473","real":false,"r":"perp","col":false,"whole":false,"mult":1,"v":0.46,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"ABCL","n":"AbCellera Biologics","s":"Biotechnology","p":16.54,"a":"0x31bfdf8a3f45bf3dde074dc7a133abd5590e95d6","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"ADBE","n":"Adobe","s":"Software","p":402.7,"a":"0x48485504f373c80371f27f315f6dcf2389c5af61","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"AEHR","n":"Aehr","s":"Semiconductors","p":221.42,"a":"0x6e92a478f29dc51a9d2703f6b40367ae12cbef68","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.46,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"AEIS","n":"Advanced Energy","s":"Semiconductors","p":339.45,"a":"0x1f1f975500953b31bc0ba7b54aacf7f16e7293eb","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.46,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"ALAB","n":"Astera Labs","s":"Semiconductors","p":344.95,"a":"0x4ad460c4814ca0f1c1819c4785aebe1c27fbb5af","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.46,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"AMAT","n":"Applied Materials","s":"Semiconductors","p":323.13,"a":"0x4219de1477f9914a93c6dfc439c5092082fe45ff","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.46,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"AMBA","n":"Ambarella","s":"Semiconductors","p":272.06,"a":"0x6db69b7327ab143862a223d971602b6bcdc4a0c0","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.46,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"AMC","n":"AMC Entertainment","s":"Entertainment","p":3.42,"a":"0x47665a8aa316a9a076eb8b2e2d3c622c8a1c3d73","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"AMD","n":"AMD","s":"Semiconductors","p":198.35,"a":"0xf8b3fda475d85d2b07f55448ae7735cb58c6e133","real":false,"r":"perp","col":false,"whole":false,"mult":1,"v":0.46,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"AMKR","n":"Amkor Technology","s":"Semiconductors","p":96.91,"a":"0x8559d2fc24dce3549016ddc952b4e2611e9eb121","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.46,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"ANET","n":"Arista","s":"Networking","p":257.83,"a":"0x66d7207f31cedfdb46f71823cbec2bcacf117426","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"APLD","n":"Applied Digital","s":"Data Centers","p":309.8,"a":"0x2dd863ad4134b2b9636a0c269d89d95d79be8edf","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"APP","n":"AppLovin","s":"Software","p":312.06,"a":"0xb81ec059f59a7a4a87abf4d782f1f7128612513f","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"ASML","n":"ASML Holding NV","s":"Semiconductors","p":1042.6,"a":"0xf698d185c29f9e9b3c5f595fd8fc550e3ef1cf5b","real":false,"r":"perp","col":false,"whole":false,"mult":1.000101,"v":0.46,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"ASTS","n":"AST SpaceMobile","s":"Space & Satellite","p":43.98,"a":"0x44f53560fcd1c4c1c45f179c9bcbd87d3eb66c89","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.72,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"AUR","n":"Aurora Innovation","s":"Autonomous Vehicles","p":305.24,"a":"0x11f9ce727d48cef1f8ac4e7be5ece2442b0911c7","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"AVAV","n":"AeroVironment","s":"Aerospace & Defense","p":360.84,"a":"0x0cb45f8138658e51eef26688ea8d46cea795b803","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"AVGO","n":"Broadcom","s":"Semiconductors","p":386.24,"a":"0x6e352c53a395174dcb208a123cab3acbbf790d04","real":false,"r":"perp","col":false,"whole":false,"mult":1,"v":0.46,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"AXON","n":"Axon","s":"Aerospace & Defense","p":352.55,"a":"0xa145ed0cbc6e59f69bcf03eaae52e3fc87f9b64d","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"AXTI","n":"AXT","s":"Semiconductors","p":100.46,"a":"0xb15bdef733333d6768b91222c51d199467441e36","real":false,"r":"perp","col":false,"whole":false,"mult":1,"v":0.46,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"BA","n":"Boeing","s":"Aerospace & Defense","p":214.8,"a":"0xcdf34c30a6dff80687bdddfefa42134cbae1a147","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"BABA","n":"Alibaba","s":"Consumer Discretionary","p":187.43,"a":"0x720bcf8bfa04faf14cef0c74c26b03ad88f5471b","real":false,"r":"perp","col":false,"whole":false,"mult":1,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"BB","n":"Blackberry","s":"Cybersecurity","p":231.43,"a":"0x449fd9e2fbba85bdd8cfa2fc5a22dc471421d220","real":false,"r":"perp","col":false,"whole":false,"mult":1,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"BE","n":"Bloom Energy","s":"Clean Energy","p":88.7,"a":"0xf3ea39f545bf4d0e7edb83bf616bba83d187ee66","real":false,"r":"perp","col":false,"whole":false,"mult":1,"v":0.68,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"BND","n":"Vanguard Total Bond Market ETF","s":"ETF - Bonds","p":74.2,"a":"0xd61b583189ab05c98b843c0fac45dac10185aa09","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.06,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"BULL","n":"Webull","s":"Financials","p":191.24,"a":"0xa76c342d03b7a720b2bbd58b21d2c92f16e79dac","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"CBRS","n":"Cerebras Systems","s":"Semiconductors","p":288.01,"a":"0xcbd17a28146b2e289113995597807b5cbdfc2bc9","real":false,"r":"perp","col":false,"whole":false,"mult":1,"v":0.46,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"CCL","n":"Carnival Corporation","s":"Travel & Leisure","p":159.27,"a":"0x4707a059f759bb2baa72ff3fa57c6a7d11fb4753","real":false,"r":"none","col":false,"whole":false,"mult":1.021486,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"CEG","n":"Constellation Energy","s":"Utilities","p":342.8,"a":"0x4f140fb7a4c335711a2043a57b5718631719edba","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"CELH","n":"Celsius","s":"Consumer Staples","p":42.6,"a":"0x0738e6ad63d9ce2df73f53e19524587d64742af3","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.26,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"CIEN","n":"Ciena","s":"Networking","p":53.5,"a":"0xff0dbf576108718d90beb451e8d9dc4fd71aedc2","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"CLOV","n":"Clover Health Investments","s":"Healthcare","p":140.47,"a":"0x8a380e0aef4756520124f45bd6676801154e5b77","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.26,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"CLS","n":"Celestica","s":"Electronics Manufacturing","p":272.85,"a":"0xddd02095bdc9cd02b97379a64831928b042de4d8","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"CLSK","n":"CleanSpark","s":"Crypto Mining","p":8.22,"a":"0xcd42e16837a29aa17d9174858f33721c75e25ec5","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.88,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"COHR","n":"Coherent","s":"Photonics","p":120,"a":"0xc9d491b3603a52b6113d5dca7bc67256a713ace1","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"COST","n":"Costco","s":"Consumer Staples","p":962.4,"a":"0xd548ae040ee620dc61288d6efaf9fd0a597f3ec2","real":false,"r":"none","col":true,"whole":false,"mult":1.000612,"v":0.26,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"CRCL","n":"Circle Internet Group","s":"Crypto Financials","p":164.2,"a":"0x5c3f6c14a1fd18711405e5606beff247b8dc03d1","real":false,"r":"perp","col":false,"whole":false,"mult":1,"v":0.74,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"CRDO","n":"Credo Technology Group","s":"Semiconductors","p":49.24,"a":"0xfb204ee97f7fff630f907e26d6507fcb8d55895e","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.46,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"CRWD","n":"CrowdStrike Holdings","s":"Cybersecurity","p":428.6,"a":"0xbc5841529b03d6b8a569789e31d9ce7ec4b36557","real":false,"r":"none","col":true,"whole":false,"mult":4,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"CRWV","n":"CoreWeave","s":"Cloud & AI Infrastructure","p":148.89,"a":"0xa014df21399c11076cfb5bcc7b0abc67458ffcf9","real":false,"r":"perp","col":false,"whole":false,"mult":1,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"CSCO","n":"Cisco Systems","s":"Networking","p":74.2,"a":"0xecc74e84afe6587410ad150e703ed3ef7146e26d","real":false,"r":"none","col":true,"whole":false,"mult":1,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"CTSH","n":"Cognizant","s":"IT Services","p":227.15,"a":"0x8b21ee62e94f8eb88de1fdd356631e7435b38b6e","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"CVNA","n":"Carvana","s":"Consumer Discretionary","p":386.4,"a":"0x43fcbb9537d45995b1660debc750dc5330266899","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"DDOG","n":"Datadog","s":"Software","p":142.6,"a":"0x253dfa347d9cdafe0d42859380af4ad7bf75b7ed","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"DELL","n":"Dell","s":"Hardware","p":142.3,"a":"0x9934b55e983b6ff521e431fc6181bcec7265dc07","real":false,"r":"perp","col":false,"whole":false,"mult":1,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"DJT","n":"Trump Media & Technology Group","s":"Media","p":18.6,"a":"0x0449712ac7417b64e3307f7b535399f18947ac98","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"DOCN","n":"DigitalOcean","s":"Cloud & AI Infrastructure","p":255.26,"a":"0x0e1ae11df5179e70f60f5c0fe4543c66b847c02a","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"ELF","n":"e.l.f. Beauty","s":"Consumer Staples","p":86.4,"a":"0xa7789b5e20fd5f466ef923eb637bb83206cfda42","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.26,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"EWT","n":"iShares MSCI Taiwan Capped ETF","s":"ETF - International Equity","p":208.36,"a":"0x73fb933eee6aa31912f810dcfea80905a1372ff4","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.19,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"EWY","n":"iShares MSCI South Korea Fund","s":"ETF - International Equity","p":214.31,"a":"0xe5a99d356b95436e9d0bd23ce5db753386ca3af7","real":false,"r":"perp","col":false,"whole":false,"mult":1,"v":0.19,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"F","n":"Ford Motor","s":"Automotive","p":12.84,"a":"0x1464a8ce4cd8fd43a41418f33c893a9cd157a304","real":false,"r":"none","col":false,"whole":false,"mult":1.000146,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"FICO","n":"Fair Isaac","s":"Financials","p":85.03,"a":"0x81c38d40054b32260bb097b2237b469ef9ee524f","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"FIG","n":"Figma","s":"Software","p":232.99,"a":"0x4dbe30c4ed05e69b68ff4a446f4135dd5212cebd","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"FISV","n":"Fiserv Inc.","s":"Fintech","p":178.11,"a":"0x8befacf5804633c0a76695134ec36e1cc3e3fb9b","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"FIX","n":"Comfort Systems","s":"Industrials","p":289.03,"a":"0x38288768841613448b0302ca4073927d00c2cfa1","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"FLNC","n":"Fluence Energy","s":"Clean Energy","p":7.61,"a":"0x4799a19a33797f191d68deb0cbcda1d31f2093c3","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.68,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"FLY","n":"Firefly Aerospace","s":"Space & Satellite","p":34.21,"a":"0x1338cedd1b0efa74296b583e9ce198158b87861b","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.72,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"FTNT","n":"Fortinet","s":"Cybersecurity","p":98.4,"a":"0xafc75341032ee42607578e612c31af95cf4a9dea","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"FUTU","n":"Futu Holdings","s":"Financials","p":75.17,"a":"0x7eebd4336300b9b75a76de5083b49614b9cc12a7","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"GE","n":"General Electric","s":"Industrials","p":298.4,"a":"0xfe9602ffa25582072183c916279b75f91de01aed","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"GEV","n":"GE Vernova","s":"Power & Electrification","p":95.48,"a":"0xf76f66d490003d8178d1d7444e0ec2a9973b3938","real":false,"r":"perp","col":false,"whole":false,"mult":1,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"GLD","n":"SPDR Gold Trust","s":"ETF - Commodities","p":384.6,"a":"0x128a7931d1696b4b9696f5d2d617aec06da67ea4","real":false,"r":"none","col":true,"whole":false,"mult":1,"v":0.18,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"GLW","n":"Corning","s":"Photonics","p":47.43,"a":"0xf0a05725d776db2c3e8373fd12d9b9a8e51af744","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"GLXY","n":"Galaxy Digital","s":"Crypto Financials","p":293.18,"a":"0x1bdf40476ce8df1c7eca8b10abb64df080135050","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.74,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"GME","n":"GameStop","s":"Consumer Discretionary","p":24.8,"a":"0x3b42f3b1f7978b3bd8c7b63cf8314e6bf42939e2","real":false,"r":"perp","col":false,"whole":false,"mult":1,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"HII","n":"Huntington Ingalls","s":"Aerospace & Defense","p":201.55,"a":"0xfebe59a8bec8383157d1927728a8b3f38528cb07","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"HIMS","n":"Hims & Hers Health","s":"Healthcare","p":59.72,"a":"0x0fd11450c5af052c3b9fd58c124b8581df886953","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.26,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"HOOD","n":"Robinhood Markets","s":"Financials","p":128.3,"a":"0xd883048531f43efa6a514d7f56ac27a63b431f30","real":false,"r":"none","col":true,"whole":false,"mult":1,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"HPE","n":"HP Enterprise","s":"Hardware","p":24.8,"a":"0xe1cdf446ce6f73314c1f7bd9f0c1842fb9562a17","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"HWM","n":"Howmet Aerospace","s":"Aerospace & Defense","p":360.13,"a":"0x28f3a5559158b286ff62bb84b026d6a0dfbe0997","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"IBM","n":"IBM","s":"Technology","p":286.4,"a":"0xcb7685d128376bf04053fdca444615963b446d18","real":false,"r":"perp","col":false,"whole":false,"mult":1,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"IBRX","n":"ImmunityBio","s":"Biotechnology","p":137.73,"a":"0x99bd19084ff3b10571ed581da29c20caa4ffc1db","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"INDA","n":"iShares MSCI India ETF","s":"ETF - International Equity","p":359.65,"a":"0xdca92ff53544e12abf11b5b84c883b3e2ea82eb0","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.19,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"INFQ","n":"Infleqtion","s":"Quantum Computing","p":28.26,"a":"0x580f89daee848a50867cd72ae2c092ab64b83ded","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.95,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"INOD","n":"Innodata","s":"AI Services","p":262.45,"a":"0x9866397f82093059f7c80d57b7f554c485142c44","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"INTC","n":"Intel","s":"Semiconductors","p":38.75,"a":"0x7f536831b828e34e3b12d3ede07f666233f50f3f","real":false,"r":"perp","col":false,"whole":false,"mult":1,"v":0.46,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"INTU","n":"Intuit","s":"Software","p":220.14,"a":"0xc7c44ad3cf0b4058048a47de4f1d71233325073f","real":false,"r":"none","col":true,"whole":false,"mult":1,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"IONQ","n":"IonQ","s":"Quantum Computing","p":48.2,"a":"0x82e3a4b274c0b9ca5476fbae01a7cc2bec764645","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.95,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"IREN","n":"IREN Limited","s":"Data Centers","p":28.04,"a":"0x136f530b43b054e831140e1252fc38a70792de7b","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"JBL","n":"Jabil Inc.","s":"Electronics Manufacturing","p":47.49,"a":"0x3c6448eec36504e9f57ec0573d72ad1d6fe747a2","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"JNJ","n":"Johnson & Johnson","s":"Healthcare","p":168.4,"a":"0xcd435d45a5ed236525c8a2b4b565cfa738c1d9b2","real":false,"r":"none","col":true,"whole":false,"mult":1,"v":0.26,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"JOBY","n":"Joby Aviation","s":"Aerospace & Defense","p":404.19,"a":"0x0719aa3f676f567af699b7a28224258a52b825bd","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"KLAC","n":"KLA","s":"Semiconductors","p":89.12,"a":"0xb2ab422220f80d6286aa79a5db80d2d557186a2c","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.46,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"KSS","n":"Kohls Corp.","s":"Consumer Discretionary","p":199.52,"a":"0xec9dc97a05bbd07e985f36878eda76259ae5612f","real":false,"r":"none","col":false,"whole":false,"mult":1.00461,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"KTOS","n":"Kratos Defense & Security","s":"Aerospace & Defense","p":56.46,"a":"0x44388b91478f8b6d2ac44d0efa59464ed82d5781","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"LHX","n":"L3Harris","s":"Aerospace & Defense","p":363.15,"a":"0xb3e7dbd8b5615e20dbee7fbf0e4cd1502e10787f","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"LITE","n":"Lumentum","s":"Photonics","p":298.96,"a":"0xa7a5a62bf8b82cf402ddca1a8bc7797f4943bf2b","real":false,"r":"perp","col":false,"whole":false,"mult":1,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"LLY","n":"Eli Lilly","s":"Healthcare","p":892.4,"a":"0x540f176ded6d5e28ef5f4510892cddfad5407e44","real":false,"r":"none","col":true,"whole":false,"mult":1,"v":0.26,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"LMT","n":"Lockheed","s":"Aerospace & Defense","p":486.2,"a":"0xc381b99d6c624f8d2593f9fb27eb4ef8b9345207","real":false,"r":"none","col":true,"whole":false,"mult":1,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"LRCX","n":"Lam Research Corp","s":"Semiconductors","p":130.15,"a":"0x2773a006e45ba6f5877966506d6f29de9938621d","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.46,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"LULU","n":"Lululemon","s":"Consumer Discretionary","p":214.5,"a":"0xe604d4165d3db4dd17f0f49a93fe3cb535c7d36a","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"LUNR","n":"Intuitive Machines","s":"Space & Satellite","p":9.83,"a":"0x02b3e7c6070a4438089f56186d6293a6bdbe14c8","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.72,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"MDB","n":"MongoDB","s":"Software","p":302.53,"a":"0x6464973960389004ab197124e146ab1ce6aa0ce1","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"MOD","n":"Modine","s":"Industrials","p":34.72,"a":"0x4eddf514b139034f5486cb92cf9db41ec3040f17","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"MPWR","n":"Monolithic Power Systems","s":"Semiconductors","p":170.72,"a":"0x9dbe3f8c1bd7dd55a5adb0702a3fe8b5d373fe24","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.46,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"MRNA","n":"Moderna","s":"Biotechnology","p":121.51,"a":"0xebd6011e5a8d0ff24d71ee5ee629e6f24dea86d9","real":false,"r":"perp","col":false,"whole":false,"mult":1,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"MRVL","n":"Marvell Technology","s":"Semiconductors","p":108.6,"a":"0xce01c968107de2d5372d076f699708d185196805","real":false,"r":"perp","col":false,"whole":false,"mult":1,"v":0.46,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"MTSI","n":"MACOM","s":"Semiconductors","p":38.56,"a":"0xcaf2d7663867af254b1d2710b11c231fa155460c","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.46,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"MU","n":"Micron Technology","s":"Semiconductors","p":156.42,"a":"0xbc081feb8f8f3c1ff182f38b6a7a8c44a6a8ea4d","real":false,"r":"perp","col":false,"whole":false,"mult":1,"v":0.46,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"MXL","n":"MaxLinear","s":"Semiconductors","p":203.57,"a":"0x60e1f51f4a8f181c57ddf982f316653abfcf188b","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.46,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"NAVN","n":"Navan","s":"Software","p":229.8,"a":"0x66b2359f11c9f46c4b5f77c7e9fa3fc2d2236f99","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"NBIS","n":"Nebius Group","s":"Cloud & AI Infrastructure","p":98.71,"a":"0xff1d2523e30822f9b7903d21c400c1da8cdc5e7b","real":false,"r":"perp","col":false,"whole":false,"mult":1,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"NET","n":"Cloudflare Inc.","s":"Cloud & AI Infrastructure","p":186.4,"a":"0x204f385c055dbca382cf1f123ce2f4053de8fa7d","real":false,"r":"none","col":true,"whole":false,"mult":1,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"NFLX","n":"Netflix","s":"Media","p":1128.64,"a":"0x44389c39cf6c9c96357aea843ae376397216386e","real":false,"r":"none","col":true,"whole":false,"mult":1,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"NNE","n":"Nano Nuclear Energy","s":"Nuclear Energy","p":282.78,"a":"0x6c8dc8089de2662912eff8c6b1b94110b6f9315d","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.68,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"NOW","n":"ServiceNow","s":"Software","p":285.39,"a":"0x579cb1a7d0afb815950207dc2ecd9f0013eea53a","real":false,"r":"perp","col":false,"whole":false,"mult":1,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"NU","n":"Nu Holdings","s":"Fintech","p":16.8,"a":"0x50430bc864c87759698dc1d7ca94a32bbc5dceee","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"NVTS","n":"Navitas Semiconductor","s":"Semiconductors","p":113.06,"a":"0x5722a26939811b1bb8c5abd6497a48431642a2f6","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.46,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"OKLO","n":"Oklo","s":"Nuclear Energy","p":96.4,"a":"0x22b8eb8c9f138b00e676fe63e07575c5723eceb7","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.68,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"ON","n":"ON Semiconductor","s":"Semiconductors","p":403.23,"a":"0xef428781c1c2e11d3059276b92a7d5a84f96a79e","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.46,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"ONTO","n":"Onto Innovation","s":"Semiconductors","p":134.78,"a":"0xdfbfd509d0d2b9bd6a9e783cb7631dd4420adcab","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.46,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"ORCL","n":"Oracle","s":"Technology","p":284.9,"a":"0xcf6e0d73c368daa3bab1bb6935557bb376816fdb","real":false,"r":"perp","col":false,"whole":false,"mult":1.002211,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"OUST","n":"Ouster","s":"Autonomous Vehicles","p":47.9,"a":"0xee38b62abe041dc1d2099739a4c787fe08d2ff2d","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"PANW","n":"Palo Alto Networks","s":"Cybersecurity","p":194.2,"a":"0x9ac55c0d1bab8d1c749170de22717748ed331ba3","real":false,"r":"none","col":true,"whole":false,"mult":1,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"PATH","n":"UiPath","s":"Software","p":19.63,"a":"0x9eea5221e3246c402059ccf3eb61746326973dbe","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"PENG","n":"Penguin Solutions","s":"Hardware","p":168.53,"a":"0x84ff37078e33a688065c2f6f5477f0c2f53e5994","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"PFE","n":"Pfizer","s":"Healthcare","p":26.42,"a":"0x1ca78d64d7fee6f34c9dbdd7f8b33dded6d57a99","real":false,"r":"none","col":true,"whole":false,"mult":1,"v":0.26,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"PL","n":"Planet Labs","s":"Space & Satellite","p":69.7,"a":"0x957666d275ae48535d8568240db88f18aabc87f1","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.72,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"PLTR","n":"Palantir Technologies","s":"Software","p":172.94,"a":"0xc10d552b94dc8cb66a5596d4103010fcf4600ae5","real":false,"r":"perp","col":false,"whole":false,"mult":1,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"POET","n":"POET Technologies","s":"Photonics","p":96.35,"a":"0xae72547dad6c257c32dc8d0c8ddc59708b0d9341","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"POWL","n":"Powell Industries","s":"Power & Electrification","p":155.17,"a":"0xcf932895606265727417e0f887ff26edbf834336","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"PR","n":"Permian Resources","s":"Energy","p":76.78,"a":"0x83b5b1124e1b89362013fe0bef8e11d9eccd7e79","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"PWR","n":"Quanta","s":"Power & Electrification","p":239.34,"a":"0x7748808ba6ceccf8318c48da9f455e71001552b3","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"QBTS","n":"D-Wave Quantum","s":"Quantum Computing","p":28.4,"a":"0x0af02f5743f4a871ce55a955f167b096b5912321","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.95,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"QUBT","n":"Quantum Computing Inc.","s":"Quantum Computing","p":41.54,"a":"0x07657e099534e43b3cce2769d5e982a944ece304","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.95,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"RBLX","n":"Roblox","s":"Gaming","p":128.7,"a":"0x6a60e10fbcbe0fe56e4b007c29ce4139088764e7","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"RCAT","n":"Red Cat","s":"Aerospace & Defense","p":221.07,"a":"0x8dc261b0fbefd1b3017d6455d41d4f386d7634e6","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"RDDT","n":"Reddit","s":"Media","p":214.3,"a":"0xa91608858534c0a0037d1aeea2ed52299f815c4c","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"RDW","n":"Redwire","s":"Space & Satellite","p":41.06,"a":"0x78637f129c75088cf4910d7637c2f9caa81e96ad","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.72,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"RGTI","n":"Rigetti Computing","s":"Quantum Computing","p":32.6,"a":"0xac3649a224318c6e9189edae027a9839cf03c09a","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.95,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"RIVN","n":"Rivian Automotive","s":"Automotive","p":14.6,"a":"0xe9dc93da8ed5359d4923894cafa8750c895fd59e","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"RKLB","n":"Rocket Lab Corporation","s":"Space & Satellite","p":62.9,"a":"0x7ac9396541a707ee9f841d9a6ceaf8d17fdb60d2","real":false,"r":"perp","col":false,"whole":false,"mult":1,"v":0.72,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"RUN","n":"Sunrun","s":"Clean Energy","p":23.45,"a":"0x781b65a35f8b678eadf19602ce751193634fb59a","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.68,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"SATS","n":"EchoStar","s":"Space & Satellite","p":39.71,"a":"0xdf8e31d74cb2e4e9e015e0e98aac7eee6df405d3","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.72,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"SCHD","n":"Schwab US Dividend Equity ETF","s":"ETF - US Equity","p":287.34,"a":"0xbf89966a673fbb6235fb28f76b325ed05efeb276","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.19,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"SGOV","n":"iShares 0-3 Month Treasury Bond","s":"ETF - Bonds","p":100.4,"a":"0xb96fdb03c31cbedb7fa8ed60ffb6b4b4f302640a","real":false,"r":"none","col":false,"whole":false,"mult":1.005102,"v":0.06,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"SHOP","n":"Shopify","s":"Consumer Discretionary","p":168.4,"a":"0xcf1ebd91174cb633bb34af62e051ecd07d8aeb5e","real":false,"r":"none","col":true,"whole":false,"mult":1,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"SHY","n":"iShares 1-3 Year Treasury Bond ETF","s":"ETF - Bonds","p":82.6,"a":"0x58ac4bde0d6041dd605d6061f8d6d7cb8db67c23","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.06,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"SIMO","n":"Silicon Motion","s":"Semiconductors","p":306.26,"a":"0x72c28810953c71351986b4379de735078a393bee","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.46,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"SKHY","n":"SK hynix (ADS)","s":"Semiconductors","p":121.2,"a":"0xa9449f60dd4c16849c8c8313dfd4e38949f73be7","real":false,"r":"perp","col":false,"whole":false,"mult":1,"v":0.46,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"SLS","n":"SELLAS Life Sciences","s":"Biotechnology","p":136.53,"a":"0x489a81df70d1e849359d3a591a9cb044fc3d1cf4","real":false,"r":"none","col":false,"whole":true,"mult":1,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"SLV","n":"iShares Silver Trust","s":"ETF - Commodities","p":42.8,"a":"0x58f881821894585f733ae2be0ae3219553cecb8d","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.18,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"SMCI","n":"Super Micro Computer","s":"Cloud & AI Infrastructure","p":41.6,"a":"0x03e3df2797837d49518271fa97abab83b2638924","real":false,"r":"none","col":true,"whole":false,"mult":1,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"SMH","n":"VanEck Semiconductor ETF","s":"ETF - Sector Equity","p":386.4,"a":"0x0f98c1b85cb9d17356ec5ad1f477b0d8e2279802","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.19,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"SMR","n":"NuScale Power","s":"Nuclear Energy","p":42.8,"a":"0xce1b8d9f162a41a426ce5ebfe445d074917fb371","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.68,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"SNAP","n":"Snap","s":"Media","p":9.84,"a":"0x2e392503aa7fcee799c383598dfb30ef21bab940","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"SNDK","n":"Sandisk Corporation","s":"Semiconductors","p":165.12,"a":"0x1ff9319d4732b19ba31ccd248e0143c31c77b476","real":false,"r":"perp","col":false,"whole":false,"mult":1,"v":0.46,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"SNOW","n":"Snowflake","s":"Software","p":168.4,"a":"0x71675ac48be692d4ecc3d66e805d5c5621c7bf83","real":false,"r":"none","col":true,"whole":false,"mult":1,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"SOFI","n":"SoFi Technologies","s":"Fintech","p":24.6,"a":"0x54295fad1e6f56b0f2793090bb91fe57b2cebd7c","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"SOUN","n":"SoundHound AI","s":"AI Services","p":47.78,"a":"0xabc7dd203a738712220b2306441261f45b822802","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"SOXX","n":"iShares Semiconductor ETF","s":"ETF - Sector Equity","p":116.37,"a":"0xa7a60d94f96c1744d4930ec2d99bb91a0b732114","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.19,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"SPMO","n":"Invesco S&P 500 Momentum ETF","s":"ETF - US Equity","p":201.83,"a":"0x36f69f69e3d8985642e55e5d224a7534a0adcc8c","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.19,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"TE","n":"T1 Energy","s":"Clean Energy","p":19.96,"a":"0xd7fa24f1808b9a1e441f76d86eb95993d466a775","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.68,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"TEAM","n":"Atlassian Corporation","s":"Software","p":93.13,"a":"0x1890000761516f6416ef16e577f231e62b7f99d6","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"TEM","n":"Tempus AI","s":"Healthcare AI","p":249.08,"a":"0xee311611f9052aba107610195cf62b6d3251c130","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"TER","n":"Teradyne","s":"Semiconductors","p":70.9,"a":"0x1131a2d7d51e52ccd33a031ec3993bcbcd435cdb","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.46,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"TSEM","n":"Tower Semiconductor","s":"Semiconductors","p":152.42,"a":"0xc8dbd07a1630ffe4a8d0c3bcab7f9065139bd911","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.46,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"TSM","n":"Taiwan Semiconductor Manufacturing","s":"Semiconductors","p":328.4,"a":"0xe8bc83f4214a6f5109f01ba856611f5a0f258296","real":false,"r":"perp","col":false,"whole":false,"mult":1,"v":0.46,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"TTD","n":"Trade Desk","s":"AdTech","p":139.88,"a":"0x6c37e4e6e736329eef0630587d146a5857aa131e","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"TTWO","n":"Take-Two Interactive Software","s":"Gaming","p":23.08,"a":"0xdb6e9ed7993f02873e5e2c200146874247c1a6ab","real":false,"r":"perp","col":false,"whole":false,"mult":1,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"UMC","n":"United Microelectronics","s":"Semiconductors","p":52.94,"a":"0x47d0917ec214c46e92506bbdd8c3cb27f4b7b59f","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.46,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"UNH","n":"UnitedHealth","s":"Healthcare","p":342.7,"a":"0x7edb8f18b65785fdb8f67b0258686264fb534f5f","real":false,"r":"none","col":true,"whole":false,"mult":1,"v":0.26,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"UPS","n":"UPS","s":"Logistics","p":202.35,"a":"0x32d98de6cb46cbfeb12499d8b832f20afa27876a","real":false,"r":"none","col":false,"whole":false,"mult":1.002209,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"USAR","n":"USA Rare Earth","s":"Materials & Mining","p":106.54,"a":"0xbdf2d37437203dbabc266ed5f4dffad9b4b4af43","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"USO","n":"United States Oil Fund","s":"ETF - Commodities","p":78.4,"a":"0x1df91bdda73009f841aae0e8d8996b2ca5df7af0","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.18,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"VICR","n":"Vicor","s":"Power & Electrification","p":74.15,"a":"0xa3db01f808f40bb803aaa87b0de574adfca4dfb7","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"VRT","n":"Vertiv","s":"Data Centers","p":173.23,"a":"0xf4ee7f018a197dce781ace9dc4bd0a538efc38a0","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"VSAT","n":"ViaSat","s":"Space & Satellite","p":27.36,"a":"0xe5f8bd1c839c48955cbf51cdbeab476b4f4064c8","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.72,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"VST","n":"Vistra","s":"Utilities","p":218.6,"a":"0x3e201c730ffac391b6aae65e7f48b70d5a2a3130","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"VTI","n":"Vanguard Total Stock Market ETF","s":"ETF - US Equity","p":348.2,"a":"0x31a0b7f718bd8d9bd7dd2614608a1966a93755ea","real":false,"r":"none","col":true,"whole":false,"mult":1,"v":0.19,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"WDAY","n":"Workday","s":"Software","p":251.69,"a":"0x69e9a5f4c4079cf3c26c47632aa2a3cc1a2ea508","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"WDC","n":"Western Digital","s":"Semiconductors","p":205.82,"a":"0x7e92bc407542fc9c9dd90c1142e84a59f05d96dc","real":false,"r":"perp","col":false,"whole":false,"mult":1.000218,"v":0.46,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"WULF","n":"TeraWulf","s":"Crypto Mining","p":15.86,"a":"0x9fe1cb8045905624ddf1f3b35ee2325574257213","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.88,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"WYFI","n":"WhiteFiber Inc.","s":"Data Centers","p":141.48,"a":"0x3d572efe2891f095b7b6458394938f376d3e5061","real":false,"r":"none","col":false,"whole":true,"mult":1,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"XLK","n":"Technology Select Sector SPDR ETF","s":"ETF - Sector Equity","p":328.9,"a":"0xbb8256d73f778972ed7695cc22799ffa868d8ce1","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.19,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"XNDU","n":"Xanadu Quantum","s":"Quantum Computing","p":28.33,"a":"0x8344d11e1977eaa649bd7684f7d424e4fdca04d7","real":false,"r":"none","col":false,"whole":true,"mult":1,"v":0.95,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"XOM","n":"Exxon Mobil Corp.","s":"Energy","p":118.62,"a":"0x8b424ac87be7b7117e79314384092561726da97d","real":false,"r":"none","col":true,"whole":false,"mult":1,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"ZM","n":"Zoom","s":"Software","p":84.2,"a":"0x7643e414fcf5d95f1699988703b8a5033add322c","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"ZS","n":"Zscaler","s":"Cybersecurity","p":268.4,"a":"0xec42aeb6e2f5ee13bf26afa30cba0d3572501df2","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.38,"c":"equity","q":"USDG","age":0,"tier":0},
  {"t":"PONS","n":"Pons","s":"Launchpad","p":0.5978,"a":"0x1616d920500e8ab434ef4898fc8c14d23d9f430a","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":1.45,"c":"coin","q":"USDG","age":71,"tier":3},
  {"t":"CASHCAT","n":"Cash Cat","s":"Memecoin","p":0.04128,"a":"0x5c685b84fdf75a8c8cee80e40a7a98a86481b280","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":1.42,"c":"coin","q":"USDG","age":68,"tier":3},
  {"t":"WETH","n":"Wrapped Ether","s":"Infrastructure","p":2431.6,"a":"0x2ba03c5dff6ecc144748e516ddeea74c822108cb","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":0.62,"c":"coin","q":"USDG","age":71,"tier":3},
  {"t":"AI","n":"Artificial Inu","s":"Stock-paired meme","p":0.013842,"a":"0xf3848311f9576e22250a83f85a62ad8be7ac3803","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":1.58,"c":"coin","q":"NVDA","age":58,"tier":2},
  {"t":"DOGO","n":"Dogo","s":"Memecoin","p":0.009164,"a":"0x8fd069caae093dd74142cb3570015569650db45f","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":1.58,"c":"coin","q":"USDG","age":62,"tier":2},
  {"t":"PIPEDOG","n":"Pipedog","s":"Memecoin","p":0.002471,"a":"0x34fb34ce305ccd9eff2075b89ad113c4fcc23c74","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":1.58,"c":"coin","q":"USDG","age":55,"tier":2},
  {"t":"MOW","n":"Mow","s":"Memecoin","p":0.00084217,"a":"0x05631fc794bbbf0a674b5458a877da25595cd247","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":1.58,"c":"coin","q":"USDG","age":41,"tier":2},
  {"t":"TENDIES","n":"Tendies","s":"Memecoin","p":0.00196402,"a":"0xd4bf16288e926936abcfa45313c002ff2c57fa3b","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":1.58,"c":"coin","q":"USDG","age":49,"tier":2},
  {"t":"HMM","n":"Hmm","s":"Memecoin","p":0.00031845,"a":"0xd1e9ace48f60a40ce5f0d38f6cdba19cfbde2299","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":1.74,"c":"coin","q":"USDG","age":33,"tier":1},
  {"t":"STONKBROKER","n":"Stonkbroker","s":"Stock-paired meme","p":0.00006428,"a":"0xb649ef685fc6012c46f0ee71c8e5114e2c330272","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":1.74,"c":"coin","q":"SPY","age":27,"tier":1},
  {"t":"MEME","n":"Meme","s":"Memecoin","p":0.00412069,"a":"0xd436740618bb933032c4cc561f4973dfd231815c","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":1.74,"c":"coin","q":"USDG","age":24,"tier":1},
  {"t":"CINEMA","n":"Cinema","s":"Memecoin","p":0.00008912,"a":"0x4646c7c0f557560b934ff289912c14ba38496165","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":1.74,"c":"coin","q":"USDG","age":16,"tier":1},
  {"t":"SHRUB","n":"Shrub","s":"Memecoin","p":0.00001274,"a":"0xda44e78290f401b9412603904e4b3a96761d42b4","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":1.74,"c":"coin","q":"USDG","age":9,"tier":1},
  {"t":"BAGHOLDER","n":"Bagholder","s":"Stock-paired meme","p":0.00002186,"a":"0x4da231c4dce192e0fcb3b2fd97e0c0557c3890f0","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":1.9,"c":"coin","q":"TSLA","age":12,"tier":0},
  {"t":"DIAMONDHANDS","n":"Diamond Hands","s":"Memecoin","p":0.00000914,"a":"0xffb6af655bd4cb58cd0589afa2cf07eb290f778f","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":1.9,"c":"coin","q":"USDG","age":6,"tier":0},
  {"t":"MARGINCALL","n":"Margin Call","s":"Stock-paired meme","p":0.00000472,"a":"0xcf91aba6132d9aacca458700ed57462f4ea71df5","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":1.9,"c":"coin","q":"QQQ","age":4,"tier":0},
  {"t":"GAMMA","n":"Gamma Squeeze","s":"Memecoin","p":0.00000238,"a":"0x616428c2f7ccde6ff43ab588d9636b76058f867b","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":1.9,"c":"coin","q":"USDG","age":3,"tier":0},
  {"t":"PAPERHANDS","n":"Paper Hands","s":"Memecoin","p":0.00000117,"a":"0x057dcc824b7c16ea6e829caafd4c3071b3e17732","real":false,"r":"none","col":false,"whole":false,"mult":1,"v":1.9,"c":"coin","q":"USDG","age":2,"tier":0},
]

function build(seed: Seed): Asset {
  const next = rng(`rhc:${seed.t}:mkt`)
  const isCoin = seed.c === 'coin'

  const vol = seed.v * between(next, 0.85, 1.25)
  const drift = between(next, -0.24, 0.34)
  const isEtf = seed.s.startsWith('ETF')

  // A memecoin does not move like a share. Nothing arbitrages it back to a
  // fair value, so the daily range is measured in tens of percent and the
  // youngest names are the wildest.
  const swing = isCoin ? (seed.tier >= 2 ? 26 : 55) : isEtf ? 2.7 : 9
  const change24h = between(next, -swing, swing)
  const change1h = change24h * between(next, 0.05, 0.5) + between(next, -1.4, 1.4) * (isCoin ? 6 : 1)
  const change7d = change24h * between(next, 0.6, 2.4)

  // Depth. For equities the short route is a decent proxy for attention; for
  // coins it is simply how established the token is.
  const tier = isCoin
    ? [0.02, 0.12, 0.8, 4][seed.tier] ?? 0.05
    : seed.r === 'borrow'
      ? 6
      : seed.r === 'perp'
        ? 2.4
        : 0.7
  const liquidity = between(next, 0.4e6, 18e6) * tier
  // Coins turn over their own float many times a day. Equities do not.
  const volume24h = liquidity * (isCoin ? between(next, 1.2, 14) : between(next, 0.4, 5.6))
  const marketCap = liquidity * (isCoin ? between(next, 8, 60) : between(next, 40, 900))

  // Borrow is the price of a short, so it is expensive exactly where shorting is
  // hard — which on this chain is almost everywhere, and worst of all on coins
  // that no lender will touch.
  const borrowFee = isCoin
    ? between(next, 0.6, 3.2) - seed.tier * 0.12
    : seed.r === 'none'
      ? between(next, 0.22, 0.95)
      : seed.r === 'perp'
        ? between(next, 0.03, 0.28)
        : between(next, 0.005, 0.06)

  const shortInterest = isCoin
    ? between(next, 0.0, 0.08)
    : seed.r === 'none'
      ? between(next, 0.02, 0.18)
      : between(next, 0.12, 0.66)
  const fundingRate = (shortInterest - 0.5) * -between(next, 0.0004, 0.0055)

  return {
    symbol: seed.t,
    underlying: isCoin ? undefined : seed.t,
    name: seed.n,
    /** The on-chain ERC-20 name. Stock tokens carry the issuer suffix; coins do not. */
    tokenName: isCoin ? seed.n : `${seed.n} • Robinhood Token`,
    sector: seed.s,
    assetClass: seed.c,
    quote: seed.q,
    ageDays: isCoin ? seed.age : undefined,
    private: seed.t === 'SPCX',
    address: seed.a,
    verifiedAddress: seed.real,
    logoHue: Math.floor(next() * 360),
    price: seed.p,
    anchor: seed.p,
    change1h,
    change24h,
    change7d,
    volume24h,
    liquidity,
    marketCap,
    holders: Math.floor(
      between(next, 240, 96_000) * (isCoin ? 0.05 + seed.tier * 0.4 : seed.r === 'none' ? 0.4 : 1),
    ),
    borrowFee,
    fundingRate,
    shortInterest,
    openInterest: liquidity * between(next, 0.2, 1.8),
    phase: 'open' as MarketPhase,
    vol,
    drift,
    shortRoute: seed.r,
    collateralOnly: seed.col,
    wholeSharesOnly: seed.whole,
    uiMultiplier: seed.mult,
  }
}

export const ASSETS: Asset[] = SEEDS.map(build)

export const ASSET_BY_SYMBOL: Record<string, Asset> = Object.fromEntries(
  ASSETS.map((a) => [a.symbol, a]),
)

export function getAsset(symbol: string): Asset | undefined {
  return ASSET_BY_SYMBOL[symbol]
}

export const SECTORS: string[] = ["AI Services", "AdTech", "Aerospace & Defense", "Automotive", "Autonomous Vehicles", "Biotechnology", "Clean Energy", "Cloud & AI Infrastructure", "Consumer Discretionary", "Consumer Staples", "Crypto Financials", "Crypto Mining", "Crypto Treasury", "Cybersecurity", "Data Centers", "ETF - Bonds", "ETF - Commodities", "ETF - International Equity", "ETF - Sector Equity", "ETF - US Equity", "Electronics Manufacturing", "Energy", "Entertainment", "Financials", "Fintech", "Gaming", "Hardware", "Healthcare", "Healthcare AI", "IT Services", "Industrials", "Infrastructure", "Launchpad", "Logistics", "Materials & Mining", "Media", "Memecoin", "Networking", "Nuclear Energy", "Photonics", "Power & Electrification", "Quantum Computing", "Semiconductors", "Software", "Space & Satellite", "Stock-paired meme", "Technology", "Travel & Leisure", "Utilities"]

/** Sectors that belong to native coins rather than tokenized equities. */
export const COIN_SECTORS: string[] = ["Infrastructure", "Launchpad", "Memecoin", "Stock-paired meme"]

export const EQUITIES: Asset[] = ASSETS.filter((a) => a.assetClass === 'equity')
export const COINS: Asset[] = ASSETS.filter((a) => a.assetClass === 'coin')

export const SHORT_ROUTE_LABEL: Record<ShortRoute, string> = {
  borrow: 'Spot borrow',
  perp: 'Perp only',
  none: 'No short route',
}

/**
 * Equity market phase for a given moment, US Eastern.
 *
 * Stock Tokens trade on-chain 24/7, but the underlying venue does not — and the
 * mint/burn window that lets authorised participants arbitrage the peg is only open
 * Monday 02:00 CET through Saturday 02:00 CET. Outside it, nothing keeps the token
 * tied to the share, and spreads widen. That is a real property of this asset class
 * and the interface has to say so.
 */
export function marketPhase(now = new Date()): MarketPhase {
  const et = new Date(now.toLocaleString('en-US', { timeZone: 'America/New_York' }))
  const day = et.getDay()
  const minutes = et.getHours() * 60 + et.getMinutes()
  if (day === 0 || day === 6) return 'closed'
  if (minutes >= 570 && minutes < 960) return 'open'
  if (minutes >= 240 && minutes < 570) return 'pre'
  if (minutes >= 960 && minutes < 1200) return 'after'
  return 'closed'
}

export const PHASE_LABEL: Record<MarketPhase, string> = {
  open: 'Market open',
  pre: 'Pre-market',
  after: 'After hours',
  closed: 'Market closed',
}

/**
 * Whether the mint/burn window is open. When it is shut there is no authorised
 * participant arbitrage, so the token can drift from the share it tracks.
 */
export function tokenizationWindowOpen(now = new Date()): boolean {
  const cet = new Date(now.toLocaleString('en-US', { timeZone: 'Europe/Paris' }))
  const day = cet.getDay()
  const hour = cet.getHours()
  if (day === 6) return hour < 2
  if (day === 0) return false
  if (day === 1) return hour >= 2
  return true
}
