/**
 * Regenerates lib/assets.ts from the Robinhood Chain coin registries captured
 * during research: the chain's native coins and the Pons launchpad's public
 * launch feed, with the contract addresses that were read on-chain.
 *
 * The tokenized equities are deliberately absent: SHORTCOIN only lists coins.
 * `scripts/registry.txt` is kept because the launch feed quotes several pools
 * against stock tokens, and their tickers have to resolve to a name somewhere.
 *
 * Run with: npx tsx scripts/gen-assets.ts
 * Prices and market stats are invented; identity data is not.
 */

import { writeFileSync, readFileSync } from 'node:fs'
import { rng, between } from '../lib/rng'

const COINS = readFileSync(new URL('./coins.txt', import.meta.url), 'utf8')
const PONS = readFileSync(new URL('./pons-launches.txt', import.meta.url), 'utf8')

/** The moment the Pons snapshot was taken, used to age every launch from. */
const SNAPSHOT = Date.parse('2026-09-10T22:00:00Z')

interface CoinRow {
  ticker: string
  name: string
  sector: string
  price: number
  quote: string
  ageDays: number
  tier: number
  address?: string
}

const coinRows: CoinRow[] = COINS.split('\n')
  .map((l) => l.trim())
  .filter((l) => l && !l.startsWith('#'))
  .map((l) => {
    const [ticker, name, sector, price, quote, ageDays, tier, address] = l
      .split('|')
      .map((x) => x.trim())
    return {
      ticker,
      name,
      sector,
      price: Number(price),
      quote,
      ageDays: Number(ageDays),
      tier: Number(tier),
      address: address || undefined,
    }
  })

function fakeAddress(next: () => number): string {
  const chars = '0123456789abcdef'
  let out = '0x'
  for (let i = 0; i < 40; i++) out += chars[Math.floor(next() * 16)]
  return out
}

/**
 * Coins are a different animal. Nothing anchors them to a share, so volatility
 * is measured in whole multiples rather than percentages, depth is thin, and a
 * token can be four days old. None of them can be shorted anywhere: no perp
 * lists a Robinhood Chain memecoin and no lender will take one as a borrow.
 */
const coinSeeds = coinRows.map((r) => {
  const next = rng(`rhc:coin:${r.ticker}`)
  const vol =
    r.sector === 'Infrastructure' ? 0.62 : r.sector === 'Launchpad' ? 1.45 : 1.9 - r.tier * 0.16
  return {
    ticker: r.ticker,
    name: r.name,
    sector: r.sector,
    price: r.price,
    address: r.address ?? fakeAddress(next),
    real: !!r.address,
    route: 'none' as const,
    collateralOnly: false,
    wholeSharesOnly: false,
    uiMultiplier: 1,
    vol: Number(vol.toFixed(3)),
    cls: 'coin' as const,
    quote: r.quote,
    // coins.txt records age in days; the Asset carries hours.
    age: r.ageDays * 24,
    tier: r.tier,
  }
})

/**
 * Tokens deployed through the Pons launchpad, straight from its public API.
 *
 * These are the long tail: hours old, five-figure market caps, most of them
 * still climbing a bonding curve toward graduation, and — the detail that only
 * exists on this chain — a majority quoted against SPCX and other stock tokens
 * rather than a stablecoin.
 */
const ponsSeeds = PONS.split('\n')
  .map((l) => l.trim())
  .filter((l) => l && !l.startsWith('#'))
  .map((l) => {
    const [ticker, name, price, mcap, graduated, gradPct, quote, launchedAt, address] = l
      .split('|')
      .map((x) => x.trim())
    const next = rng(`rhc:pons:${ticker}`)
    const hours = Math.max(
      Math.round((SNAPSHOT - Date.parse(`${launchedAt}T00:00:00Z`)) / 3_600_000),
      1,
    )
    const graduatedFlag = graduated === '1'
    return {
      ticker,
      name,
      // A launch quoted against a stock token is its own category; the rest are
      // just memecoins, graduated or not.
      sector: !['USDG', 'ETH', 'cbBTC', 'WETH'].includes(quote)
        ? 'Stock-paired meme'
        : graduatedFlag
          ? 'Memecoin'
          : 'Launchpad',
      price: Number(price),
      address,
      real: true,
      route: 'none' as const,
      collateralOnly: false,
      wholeSharesOnly: false,
      uiMultiplier: 1,
      // Nothing is more volatile than a token that is hours old.
      vol: Number((hours < 48 ? between(next, 2.6, 4.4) : between(next, 1.5, 2.6)).toFixed(3)),
      cls: 'coin' as const,
      quote,
      age: hours,
      tier: 0,
      mcap: Number(mcap),
      grad: Number(gradPct),
      launchpad: 'Pons',
    }
  })

const seeds = [
  ...coinSeeds.map((x) => ({ ...x, mcap: 0, grad: -1, launchpad: '' })),
  ...ponsSeeds,
]

const sectors = [...new Set(seeds.map((s) => s.sector))].sort()

const counts = {
  total: seeds.length,
  coins: coinSeeds.length + ponsSeeds.length,
}

const body = `/**
 * SHORTCOIN — the Robinhood Chain universe.
 *
 * GENERATED by scripts/gen-assets.ts. Edit that script, not this file.
 *
 * The universe is coins only: ${counts.total} of them, native to Robinhood Chain or
 * launched through Pons. Tokenized equities are not listed — SHORTCOIN does not
 * sell a short on a share.
 *
 * What is real here: the ticker symbols, the names, the sector taxonomy, the launch
 * dates and the contract addresses that were read on-chain.
 *
 * What is invented: every price, every liquidity, holder and volume figure, and every
 * rate. Those exist to populate a simulation.
 */

import type { Asset, AssetClass, MarketPhase, ShortRoute } from './types'
import { between, rng } from './rng'

export const CHAIN = {
  name: 'Robinhood Chain',
  short: 'RHC',
  /** Verified via eth_chainId returning 0x1237. */
  chainId: 4663,
  rpc: 'https://rpc.mainnet.chain.robinhood.com',
  explorer: 'https://robinhoodchain.blockscout.com',
  gasToken: 'ETH',
  /** Global Dollar is the chain's primary quote asset, not USDC. */
  settlement: 'USDG',
  settlementAddress: '0x5fc5360D0400a0Fd4f2af552ADD042D716F1d168',
  blockTimeMs: 100,
  stack: 'Arbitrum Orbit',
} as const

/** Census of the listed universe. The infinite tail is generated on top. */
export const SHORT_CENSUS = {
  total: ${counts.total},
  coins: ${counts.coins},
} as const

interface Seed {
  t: string
  n: string
  s: string
  p: number
  a: string
  real: boolean
  r: ShortRoute
  col: boolean
  whole: boolean
  mult: number
  v: number
  c: AssetClass
  q: string
  age: number
  tier: number
  /** Real market cap in USD for Pons launches; 0 when it should be derived. */
  mc: number
  /** Graduation progress 0..100, or -1 when the concept does not apply. */
  gp: number
  lp: string
}

const SEEDS: Seed[] = ${JSON.stringify(
  seeds.map((s) => ({
    t: s.ticker,
    n: s.name,
    s: s.sector,
    p: s.price,
    a: s.address,
    real: s.real,
    r: s.route,
    col: s.collateralOnly,
    whole: s.wholeSharesOnly,
    mult: s.uiMultiplier,
    v: s.vol,
    c: s.cls,
    q: s.quote,
    age: s.age,
    tier: s.tier,
    mc: s.mcap,
    gp: s.grad,
    lp: s.launchpad,
  })),
  null,
  0,
)
  .replace(/\},\{/g, '},\n  {')
  .replace(/^\[/, '[\n  ')
  .replace(/\]$/, ',\n]')}

function build(seed: Seed): Asset {
  const next = rng(\`rhc:\${seed.t}:mkt\`)
  const isCoin = seed.c === 'coin'

  const vol = seed.v * between(next, 0.85, 1.25)
  const drift = between(next, -0.24, 0.34)
  const isEtf = seed.s.startsWith('ETF')

  // A memecoin does not move like a share. Nothing arbitrages it back to a
  // fair value, so the daily range is measured in tens of percent and the
  // youngest names are the wildest.
  const swing = isCoin ? (seed.tier >= 2 ? 26 : 55) : isEtf ? 2.7 : 9
  const change24h = between(next, -swing, swing)
  const change1h = change24h * between(next, 0.05, 0.5) + between(next, -1.4, 1.4) * (isCoin ? 6 : 1)
  const change7d = change24h * between(next, 0.6, 2.4)

  // Depth. A Pons launch reports its real market cap, and everything about a
  // token that size follows from it: a $5K token has a few thousand dollars of
  // pool behind it, not a derived multiple.
  const isPons = seed.mc > 0
  const tier = isCoin
    ? ([0.02, 0.12, 0.8, 4] as const)[seed.tier] ?? 0.05
    : seed.r === 'borrow'
      ? 6
      : seed.r === 'perp'
        ? 2.4
        : 0.7

  const marketCap = isPons ? seed.mc : 0
  const liquidity = isPons
    ? marketCap * between(next, 0.06, 0.3)
    : between(next, 0.4e6, 18e6) * tier
  // Coins turn over their own float many times a day. Equities do not.
  const volume24h = liquidity * (isCoin ? between(next, 1.2, 14) : between(next, 0.4, 5.6))

  // Borrow is the price of a short, so it is expensive exactly where shorting is
  // hard — which on this chain is almost everywhere, and worst of all on coins
  // that no lender will touch.
  const borrowFee = isCoin
    ? between(next, 0.6, 3.2) - seed.tier * 0.12
    : seed.r === 'none'
      ? between(next, 0.22, 0.95)
      : seed.r === 'perp'
        ? between(next, 0.03, 0.28)
        : between(next, 0.005, 0.06)

  const shortInterest = isCoin
    ? between(next, 0.0, 0.08)
    : seed.r === 'none'
      ? between(next, 0.02, 0.18)
      : between(next, 0.12, 0.66)
  const fundingRate = (shortInterest - 0.5) * -between(next, 0.0004, 0.0055)

  return {
    symbol: seed.t,
    underlying: isCoin ? undefined : seed.t,
    name: seed.n,
    /** The on-chain ERC-20 name. Stock tokens carry the issuer suffix; coins do not. */
    tokenName: isCoin ? seed.n : \`\${seed.n} • Robinhood Token\`,
    sector: seed.s,
    assetClass: seed.c,
    quote: seed.q,
    ageHours: isCoin ? seed.age : undefined,
    graduationPct: seed.gp >= 0 ? seed.gp : undefined,
    launchpad: seed.lp || undefined,
    private: seed.t === 'SPCX',
    address: seed.a,
    verifiedAddress: seed.real,
    logoHue: Math.floor(next() * 360),
    price: seed.p,
    anchor: seed.p,
    change1h,
    change24h,
    change7d,
    volume24h,
    liquidity,
    marketCap: isPons ? marketCap : liquidity * (isCoin ? between(next, 8, 60) : between(next, 40, 900)),
    holders: isPons
      ? Math.floor(between(next, 8, 240))
      : Math.floor(
          between(next, 240, 96_000) *
            (isCoin ? 0.05 + seed.tier * 0.4 : seed.r === 'none' ? 0.4 : 1),
        ),
    borrowFee,
    fundingRate,
    shortInterest,
    openInterest: liquidity * between(next, 0.2, 1.8),
    phase: 'open' as MarketPhase,
    vol,
    drift,
    shortRoute: seed.r,
    collateralOnly: seed.col,
    wholeSharesOnly: seed.whole,
    uiMultiplier: seed.mult,
  }
}

export const ASSETS: Asset[] = SEEDS.map(build)

export const ASSET_BY_SYMBOL: Record<string, Asset> = Object.fromEntries(
  ASSETS.map((a) => [a.symbol, a]),
)

export function getAsset(symbol: string): Asset | undefined {
  return ASSET_BY_SYMBOL[symbol]
}

export const SECTORS: string[] = ${JSON.stringify(sectors, null, 0).replace(/","/g, '", "')}

/** Sectors carried by the chain's own coins, Pons launches excluded. */
export const COIN_SECTORS: string[] = ${JSON.stringify(
  [...new Set(coinSeeds.map((c) => c.sector))].sort(),
  null,
  0,
).replace(/","/g, '", "')}

export const COINS: Asset[] = ASSETS

/** Quote assets that are money rather than a company. */
export const CASH_QUOTES = ['USDG', 'ETH', 'cbBTC', 'WETH'] as const

/**
 * True when a token's pool is quoted against a tokenized equity rather than
 * money — the pairing Robinhood Chain invented. Shorting one of these is a bet
 * on the coin RELATIVE to the share it is paired with, not against the dollar.
 */
export function isStockPaired(a: Asset): boolean {
  return a.assetClass === 'coin' && !CASH_QUOTES.includes(a.quote as (typeof CASH_QUOTES)[number])
}

export const SHORT_ROUTE_LABEL: Record<ShortRoute, string> = {
  borrow: 'Spot borrow',
  perp: 'Perp only',
  none: 'No short route',
}

/**
 * Equity market phase for a given moment, US Eastern.
 *
 * Coins trade on-chain 24/7, but a stock-paired pool's reference venue does not — and the
 * mint/burn window that lets authorised participants arbitrage the peg is only open
 * Monday 02:00 CET through Saturday 02:00 CET. Outside it, nothing keeps the token
 * tied to the share, and spreads widen. That is a real property of this asset class
 * and the interface has to say so.
 */
export function marketPhase(now = new Date()): MarketPhase {
  const et = new Date(now.toLocaleString('en-US', { timeZone: 'America/New_York' }))
  const day = et.getDay()
  const minutes = et.getHours() * 60 + et.getMinutes()
  if (day === 0 || day === 6) return 'closed'
  if (minutes >= 570 && minutes < 960) return 'open'
  if (minutes >= 240 && minutes < 570) return 'pre'
  if (minutes >= 960 && minutes < 1200) return 'after'
  return 'closed'
}

export const PHASE_LABEL: Record<MarketPhase, string> = {
  open: 'Market open',
  pre: 'Pre-market',
  after: 'After hours',
  closed: 'Market closed',
}

/**
 * Whether the mint/burn window is open. When it is shut there is no authorised
 * participant arbitrage, so the token can drift from the share it tracks.
 */
export function tokenizationWindowOpen(now = new Date()): boolean {
  const cet = new Date(now.toLocaleString('en-US', { timeZone: 'Europe/Paris' }))
  const day = cet.getDay()
  const hour = cet.getHours()
  if (day === 6) return hour < 2
  if (day === 0) return false
  if (day === 1) return hour >= 2
  return true
}
`

writeFileSync(new URL('../lib/assets.ts', import.meta.url), body)
console.log(
  `wrote lib/assets.ts — ${counts.coins} coins, ${sectors.length} sectors`,
)
